aers/FFXIVClientStructs

.gitignore
ida/classinformer.csv
ida/ffxiv_idarename.py

Biggest blocker: needs to implement vtbl inheritiance so the base classes get named first.

WIP: VTable auto-naming

---

FFXIV/Client/UI/AddonNamePlate.cs
FFXIV/Client/UI/AddonWeeklyPuzzle.cs
FFXIV/Client/UI/RaptureAtkModule.cs
FFXIV/Client/UI/UIModule.cs
ida/ffxiv_idarename.py

I've stubbed out Rapture and UIModule. The sizes are either tiny or huge, likely huge. mainly so I could cast and access what was needed. I expect these structs to evolve over time as people add to it.

Getting this in before a patch

---

ida/data.yml
ida/ffxiv_idarename.py

QA'd with Pohky this time, before submitting PR.

Refactor idarename, give more control to Ghidra

---

FFXIV/Client/Game/Object/GameObjectManager.cs
ida/data.yml

size is probably not right, i just included the interesting parts

Add GameObjectManager

---

ida/data.yml
ida/ffxiv_idarename.py

I copied and executed 400 /something commands to track all these down. Still a few unknowns that I can't be bothered to deal with.

Update rename script, add ShellCommands

---

FFXIVClientStructs/FFXIV/Client/Game/Control/TargetSystem.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/ASTGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/BLMGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/BRDGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/DNCGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/DRGGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/DRKGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/GNBGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/GaugeUnion.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/MCHGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/MNKGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/NINGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/PLDGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/RDMGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/SAMGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/SCHGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/SMNGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/WARGauge.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/WHMGauge.cs

I have no idea where this fits in for real. Copied out of Dalamud.

Client::Game::Gauge::[Job]Gauge

---

FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ResourceHandle.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/ResourceGraph.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/ResourceManager.cs
FFXIVClientStructs/STD/Map.cs
FFXIVClientStructs/STD/Pair.cs

Let me know if that's okay regarding style etc.
ghidra didn't manage to create a sig for FindResourceHandle and I didn't want to make one manually and check if it's unique, so I commented it out.

Introducing STD Map and applying to resource stuff.

---

FFXIVClientStructs/FFXIV/Client/UI/AddonMateriaRetrieveDialog.cs
ida/data.yml

There's some sort of inheritance with these materia addons, but problem for later.

Add AddonMateriaRetrieveDialog

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Device.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureTextModule.cs

also fixes a mismatch between format 2 and 3

"better" sigs, source: just trust me

---

ida/README.md
ida/data.yml
ida/ffxiv_idarename.py
ida/idauser.cfg
ida/poetry.lock
ida/pyproject.toml

- requires anytree dependency now
- IDA users need to add idauser.cfg to their ida appdata folder (see readme)

Multiple inheritance idarename

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs

Update CompanionOwnerID offset

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGaugeEnums.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

Update  BLMGauge to use flags

---

FFXIVClientStructs/FFXIV/Client/UI/AddonPartyList.cs

Opened the PR for visibility but did it as a draft because I wasn't able to fully test this change.

Fixing offsets for party list addon (trust member count up from 3 to 7)

---

FFXIVClientStructs/Attributes/AgentAttribute.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHudLayout.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemSearch.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRevive.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentTeleport.cs

Doing this in a PR because I'm not sure if you'd want it
Added Agent attributes to identify agent classes for easier parsing programmatically

Add AgentAttribute

---

FFXIVClientStructs/FFXIV/Client/Game/Control/TargetSystem.cs

This is the target the camera is focusing in GPose.

Add GPoseTarget to TargetSystem

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs

Add WorldId offset to AgentLobby.cs

---

ida/ffxiv_idarename.py

Fixes a bug if data.yml contains empty nodes under globals, functions,
or classes.

Fix handling of yaml files with empty entries

---

ida/data.yml

I've been messing around with the game's Lua engine this past week so I figured I'd offer some of what I found.
Will try to follow up with more if I have time to put everything into a proper class hierarchy.

Lua Updates for data.yml

---

ida/data.yml

Think that covers all the public API.

Update data.yml with remaining Lua C API

---

ida/data.yml

Adds support for AgentMcguffin to data.yml
This agent controls display of Collection items and the Aether Compass.

Add AgentMcguffin to data.yml

---

FFXIVClientStructs/FFXIV/Client/Game/Character/BattleChara.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/Ornament.cs

Thanks to @Ottermandias for the EquipSlotData and CustomizeData offsets

Update Character offsets

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentInputBase.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentNumericInput.cs

Update AtkComponentNumericInput and AtkComponentInputBase

---

FFXIVClientStructs/FFXIV/Client/Game/Control/TargetSystem.cs
ida/data.yml

clarify name and update the signature

Change AccessObject to InteractWithObject

---

FFXIVClientStructs.Generators/FunctionGenerator/FunctionTemplates.cs
FFXIVClientStructs.Generators/StaticAddressGenerator/StaticAddressTemplates.cs
FFXIVClientStructs/Resolver.cs

add parallel initialize methods to resolver
not the best solution, but a solution
reduces the time it takes on my machine from ~5.5s to ~800ms

parallel init methods

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Demihuman.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Human.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Monster.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/MaterialResourceHandle.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Base/SchedulerState.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Base/SchedulerTimeline.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Base/TimelineController.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonSelectString.cs
ida/data.yml

I hope this stuff is fine, if not, tell me what I should do differently.
I took care to be backward compatible.

Some additions and fixes.

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

Adds the `data.yml` declaration and enum value.

Adds AgentMJICraftSchedule

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

**Edit**: Closed and re-opened after double checking to make sure the changes were still correct following the latest hotfix.  
Not sure how useful some of these addons are - mostly just did it to help in identifying other bits.

Adds mappings for 6.2 Addon vtables (Mostly MJI)

---

ida/data.yml

Add AgentWeeklyPuzzle

---

FFXIVClientStructs/FFXIV/Client/Game/MJIManager.cs

Pushing up as a draft for now; *not verified.* Too tired to continue so here we go for now
- Restore spaces over tabs because every other file uses spaces.
- Add AllowedVisitors bitfield.
- Add tracking of the player's current mode.
- Add tracking of the player's quest progression.
- Add backing bitfields for unlocked key items and recipes.
- Add MJIWorkshops struct for workshop tracking.
- Add MJIGranaries struct for granary tracking.
- Add cabin information.
- Add landmark placement and notes.
- Fix offsets on MJIBuildingPlacement.

[WIP] Even More Island Sanctuary Work

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarBase.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonActionDoubleCrossBase.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

- Some extras for Kami and another sig because why not
- Fix "IsEmpty" to check the same way the game does
- Old IsEmpty has become IsLoaded, with docs

Add some extra research for Hotbar things

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
ida/data.yml

- Still very WIP, but syncing before 6.28
- Add some core gearset behavior
There appears to be a ton related to portraits, but I haven't managed to crack that yet (though I haven't looked too deeply eihter). Hopefully this is at least a good starting point, though!

Add some Gearset research

---

ida/data.yml

Add AddonAOZContentResult (Masked Carnival Result Window)
Add AddonAOZContentBriefing (Masked Carnival Duty Select Window)
Add AddonGcArmyExpedition (Grand Company Squadron Mission Select Window)
Add AddonGcArmyExpeditionResult (Grand Company Squadron Reward Window)

Add Multiple Addons

---

FFXIVClientStructs/FFXIV/Client/Game/Group/GroupManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Group/PartyMember.cs

Fix group manager fields related to alliances.

Fix alliance stuff in group manager.

---

FFXIVClientStructs/FFXIV/Client/Game/StatusManager.cs
ida/data.yml

The methods for adding/removing status effects.

Add/Remove Status Effects

---

FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
ida/data.yml

Sorry for the rapid PRs. Just going through a bunch of work I have done recently and determining what can go back upstream.
This is a first pass on ActionTimeline (Animations) and includes CharacterMode as that's also useful for overriding timelines.

Initial ActionTimeline

---

FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs

* Correct address for 6.3 (It goes forward 20h from the old offset but then back 10h with the new structure, netting us 10h forward overall)
* Class structure now reflects the reality more closely

ActionTimelineManager tweaks

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Ornament.cs
ida/data.yml

Ornament offset updates for 6.3
Fixed a rename I made last PR and didn't reflect in data.yml

6.3 Ornament offsets

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarBase.cs
ida/data.yml

- Fix UIState offsets for the things I could
- Fix PulseActionBarSlot to 77
- Sneak in MJIManager changes

6.3 Patches from XIVDeck

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs

Fixed ActionManager::GetActionStatus signature + named unknown parameters

---

FFXIVClientStructs/FFXIV/Client/Game/Object/ClientObjectManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

Fleshed out and created an implementation for the ClientObjectManager.
Also added another flag to GameObject.

Add ClientObjectManager

---

FFXIVClientStructs/FFXIVClientStructs.csproj
FFXIVClientStructs/GitVersion.yml

Uses GitVersion to automatically version the assembly using the commit number.
PR'd for feedback in case this is undesirable

add versioning

---

ida/CExporter/Program.cs

Ghidra doesn't support importing size info with enums, so by appending 0x<size> on the enum type, it's easier to search for enums of a given size and update them after import.

[Exporter] append size info on Enums for Ghidra so they can be more easily cleaned up.

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventGPoseController.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventSceneModule.cs
ida/data.yml

Wasn't really sure what to call this one, and the second sig is pretty ugly but I couldn't find a better one.
This is the system that tracks what objects are in GPose so you can pause them, make them all walk etc.

EventGPoseController

---

FFXIVClientStructs/FFXIV/Client/Game/MJIManager.cs

This pull request aims to update MJIManager offsets for compatibility with game version 6.3, as well as correct some assumptions made in the past.

Initial pass of MJIManager for 6.3

---

FFXIVClientStructs/FFXIV/Client/Graphics/Environment/EnvManager.cs

Already in data.yml, just adding an instance accessor and a couple of known fields.

Add EnvManager

---

FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutManager.cs

This is what determines/changes the active festival (Moonfire or whatever).

Festivals / Events

---

FFXIVClientStructs/FFXIV/Client/Game/GameMain.cs

It's kind of insane to me this is the very first thing in GameMain, but it appears to be correct.

More Festival stuff

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs

I have been using these values in DailyDuty to determine if the player has collected all the available rewards for a duty.

Add values to AgentContentsFinder.cs

---

FFXIVClientStructs/FFXIV/Client/UI/AddonContentsFinder.cs

Size was determined to be 0x16C8 via AddonContentsFinder_dtor

Add AddonContentsFinder Values

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFieldMarker.cs

The agent is already in data.yml

Add AgentFieldMarker

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsFinder.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/RouletteController.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

Adds member function `GetLimitedTomestoneCount` to InventoryManager
Adds static helper functions to InventoryManager
Adds these functions to data.yml
Fixes wrong size for ContentsFinder
Adds Additional properties to ContentsFinder
Adds Missing data.yml locations for ContentsFinder
Adds RouletteController
Adds struct and instance to data.yml

Add RouletteController + Improvements

---

ida/data.yml

Have a simple one for a change =D

Add AddonContentsInfoDetail

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs

From: https://github.com/Lynesth/BetterTargetingSystem/blob/b9232611245bc63a90169903be65ffc6cd02a44e/BetterTargetingSystem/Plugin.cs#L60
```c
bool __fastcall sub_14098E880(__int64 actionId, __int64 targetObject)
{
unsigned int actionId_1; // edi
_BYTE *lumina_Action; // rax
actionId_1 = actionId;
lumina_Action = Client::ExdData::getAction(actionId);
return sub_14098E8C0(actionId_1, lumina_Action, targetObject);
}
```
`sub_14098E8C0` does all the heavy lifting, does a bunch of validation checks.

Add CanUseActionOnTarget to ActionManager

---

FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsFinder.cs

Marks byte properties as obsolete, adds new boolean properties with same offsets.

ContentsFinder Use bool

---

FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsFinder.cs
ida/data.yml

Fix ContentsFinder Offsets

---

FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsFinder.cs

Fix ContentsFinder Offset

---

FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

Checks if a specific Main Command is unlocked and usable by the player.

Add UIModule.IsMainCommandUnlocked

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs
ida/data.yml

Another super tiny change for a little bit. I'll try to merge future findings a bit more, sorry!

Add SavePendingFlag to RaptureMacroModule

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemFinderModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs

This adds a struct for `Client::UI::Misc::ItemFinderModule`.
In the beginning I just wanted to add the SearchForItem method, but ended up adding the result struct as well. 😅 
Depends on #359 (UserFileEvent)

Add ItemFinderModule

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkEvent.cs

This PR adds the already known `SetEventIsHandled` method to `AtkEvent`.

Add SetEventIsHandled

---

FFXIVClientStructs/FFXIV/Client/UI/AddonJournalDetail.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonRaidFinder.cs

AddonJournalDetail was modified in non-breaking fashion.

Add AddonRaidFinder, Update AddonJournalDetail

---

FFXIVClientStructs/FFXIV/Client/UI/AddonGcArmyCapture.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonGcArmyExpedition.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonGcArmyExpeditionResult.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonGrandCompanySupplyList.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGcArmyExpedition.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGrandCompanySupply.cs
ida/data.yml

These structs are already in data.yml

Add Grand Company Structs

---

FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs

https://github.com/goatcorp/Dalamud/pull/1143
https://gist.github.com/Loskh/c0c075d1494c9b1c63402e4bf5d06485

Add Client::UI::IsPlayerCharacterName

---

ida/data.yml

This PR adds some info about Conditions to data.yml.
Also I made some headers:
[Conditions.txt](https://github.com/aers/FFXIVClientStructs/files/10888357/Conditions.txt), a struct for g_Client::Game::Conditions
[ConditionsEnum.txt](https://github.com/aers/FFXIVClientStructs/files/10888356/ConditionsEnum.txt), an enum for arguments

Add Conditions

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
ida/data.yml

I'm simply adding them as I come across them while looking at various Addons, I'm not specifically hunting them down.
Mostly figuring out what they do via context of the nearby function calls and resulting pointers in memory.

More AtkResNode functions

---

ida/data.yml

Add RecipeNote, and a bunch of assorted funcs/vfuncs/etc.

Assorted additions to data.yml

---

FFXIVClientStructs/FFXIV/Client/UI/AddonCutSceneSelectString.cs
ida/data.yml

I wasn't able to find an associated Agent, `/xldata ai` showed `0` for the AgentAddress

Add AddonCutSceneSelectString

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Telepo.cs
ida/data.yml

Let me know if this should be done differently.

Add GetTeleportCost and describe formula.

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentSatisfactionSupply.cs
ida/data.yml

Filled in a whole bunch of details, and fixed offsets.

AgentSatisfactionSupply Updates

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCommonList.cs
ida/data.yml

As #400 pointed out InfoProxyCommonList had a few issues. This fixes the following:
* Correctly do the data arrays and add the client's native funtions for access
* Obsolete old data structures
* Add a bit more info on additional fields

Fix up InfoProxyCommonList

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMycItemBox.cs

Agent is already defined in data.yml

Add AgentMycItemBox

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

Updated offsets for PlayerState

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Inspect.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

Couldn't figure out ItemIds starting at 0x90, so I left them out.

add UIState.Inspect

---

FFXIVClientStructs/FFXIV/Client/UI/AddonContentsFinder.cs

Join and Clear were swapped... oops.

AddonContentsFinder Fix Incorrect Button Offsets

---

ida/data.yml

This might be helpful for someone looking to disable the sfx that is played when the readycheck is complete

Add AddonReadyCheck to Data.yml

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

Adds the function used by mouse hover to highlight GameObjects.
Big thanks to Wintermute and Ottermandias 💕

Add GameObject Highlight function

---

ida/data.yml

I was checking a signature for AgentAetherCurrent and found this error in the data.yml.
Obligatory disclaimer that I haven't checked any other swapperonis.

Swap AgentScenarioTree/AgentAetherCurrent address

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs

Remove setter return values in AtkResNode

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs
ida/data.yml

- Updated offsets in RaptureAtkModule, AtkModule and AgentModule
- Updated number of agents in AgentModule
- Some additions for RaptureAtkModule, AtkModule, AtkStage and InventoryManager

Various updates

---

FFXIVClientStructs/FFXIV/Client/Game/MJI/IslandState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIManager.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIPastureHandler.cs

- First pass, a few of these offsets may still be wrong.

Patch 6.4 MJIManager

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs

Fix wrong struct size being set

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs

Add CStrOverloads to AgentContext

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentTryon.cs
ida/data.yml

Kinda lazy right now, so I'm not filling that struct.
Just wanted to get the `TryOn` function in there. :)

Add AgentTryon

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
ida/data.yml

- VoiceId offset found via CharaMake function `E8 ?? ?? ?? ?? EB CB 41 83 C8 FF`.
- Updated data.yml so ReClass.NET shows names for `ActionTimelineDriver` and `ActionTimelineManager`.
🙂👍

Add VoiceId to Character, update data.yml

---

.gitignore
FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUldManager.cs
FFXIVClientStructs/STD/LinkedList.cs
ida/CExporter/Exporter.cs
ida/CExporter/Program.cs
ida/ffxiv_client_structs_arrays.h
ida/ffxiv_client_structs_arrays_ghidra.h

Fixes some small issues that were still lingering in CExporter

General CExporter final fixes

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

I added some Vfs from the data.yml to the struct.
One day, when aers has completed the inheritance generator, we can remove `ReceiveEvent` again.

Update AtkUnitBase VirtualFunctions

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs

Add delta param to AtkUnitBase.Update

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventFramework.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentOceanFishing.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentIKDFishingLog.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentIKDResult.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs

Just enough for what I need, checked over multiple boats and with the help of pohky.

Initial Ocean Fishing structs

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

A quick-ish pass over some recast-related research. In no particular order:
- Add way too many docs about how `RecastDetail` works
- Add some interesting-looking methods that might help C# devs
- Sneak in a hotbar change because why not
- Add a bunch of recast-related things to data.yml

Add recast research

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

Function copies the provided HotBarSlot to the user's saved hotbars and marks the change for saving in the data files.

Add RaptureHotbarModule->SaveSlot

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs

- Remove Span references, as they don't allow (easily) accessing pointers, which are necessary for certain methods.
- Add GetSlotById for completeness' sake

Partially revert pre-6.48 hotbar changes

---

ida/data.yml

I manually added a ton of ctors, dtors and Finalize functions and fixed the naming of existing ones.

Update data.yml (ctor/dtor/Finalize)

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkUnitManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs

Small additions

---

FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerEditor.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/BannerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaView.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaViewPortrait.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
FFXIVClientStructs/FFXIV/Common/Math/HalfVector2.cs
FFXIVClientStructs/FFXIV/Common/Math/HalfVector4.cs
ida/data.yml

Yeah, yeah. I finally PR'd it. 😜

Add AgentBannerEditor, BannerModule, CharaView(Portrait)

---

FFXIVClientStructs/FFXIV/Client/UI/AddonBannerEditor.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaView.cs
ida/data.yml

I forgot about it.
Also includes a small type fix for CharaView, but it should be fine since we just added this.

Add AddonBannerEditor

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarX.cs

Add ActionBarLayout to AddonActionBarX

---

.github/workflows/cexporter.yaml
.github/workflows/struct-update.yaml

This is a preliminary action will add one more before this should be merged which will push cexporter on new struct changes in CS

Create CExporter action

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxy11.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyInterfaces.cs
ida/data.yml

- First pass of marketboard data

Add info to InfoProxyItemSearch (MarketBoard)

---

FFXIVClientStructs/FFXIV/Application/Network/WorkDefinitions/EnterContentInfo.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentDirector.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxy11.cs
ida/data.yml

- Add EnterContentInfo packet
- Add vtbl address to InfoProxy11
- Add HandleEnterContentInfoPacket to PublicContentDirector
- Fix a stray colon in data.yml

Small extras from opcode removal

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/RootTask.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/Task.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/TaskManager.cs

This PR implements Framework's TaskManager and populates it's members.

Add Framework's TaskManager, RootTask, and Task structs

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemDetail.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismPrismItemDetail.cs

This PR creates the ItemDetail and MiragePrismPrismItemDetail agents for grabbing the hovered item id

Create ItemDetail and MiragePrismPrismItemDetail agents

---

FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ResourceHandle.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkTextureResource.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkTextureResourceManager.cs

This PR implements AtkTextureResourceManager (I'm unsure about the naming for right now), adds more vfunc definitions for ResourceHandle, and names fields in AtkTextureResource

Create AtkTextureResourceManager and update AtkTextureResource & ResourceHandle

---

FFXIVClientStructs/FFXIV/Client/UI/AddonRecipeNote.cs

Still very incomplete. I lack the patience to setup a decompiler, so this is the result of me poking at memory as much as I could, and many, many game crashes.
I'm willing to change any of the labeling / remove comments if they aren't acceptable.

Label parts of AddonRecipeNote

---

FFXIVClientStructs/FFXIV/Client/Game/Control/CameraManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs

Every other Instance getter is a method, but these aren't.
Let's fix it... next patch! 😃

Replace property Instance accessor with method

---

FFXIVClientStructs/FFXIV/Client/UI/AddonSalvageItemSelector.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentReadyCheck.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentSalvage.cs

Just found some more manually added spans that I quickly converted.
Not exactly sure what the `FixedArray` attribute does, but I replaced them with `FixedSizeArray`.

More FixedSizeArrays

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyItemSearch.cs
ida/data.yml

- GlobalItemId -> ListingId
- Town -> TownId

Tiny InfoProxyItemSearch breaking tweaks

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyItemSearch.cs
ida/data.yml

Last one, I promise.
- Adds information on the player's retainers.
- Adds some other now-discovered fields.

Yet More InfoProxyItemSearch: Player Retainer Info

---

FFXIVClientStructs.InteropSourceGenerators/AgentGettersGenerator.cs

Generate agent getter methods instead of properties

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs

- Switch to Spans
- Add `HotBar.GetHotbarSlot()` to receive a pointer for use in certain APIs.
- Rename some fields that I can't find any excuse not to.
- IsEmpty to bool.
---
N.B. Draft PR: I'm still not completely sure how this will affect consumers of the API as the Span change may be a bit annoying. I think `GetHotbarSlot()` will resolve this but I'd like to discuss this more in-depth so we don't need to do another #535.

RaptureHotbarModule v9-ification

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkEventDispatcher.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs

Didn't investigate further and don't plan on it either right now, sorry.

Add AtkEventDispatcher

---

ida/data.yml

Added some addons I use, and some I don't use.

More Addons for data.yml

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkUnitManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs

Update AtkModule, RaptureAtkModule, RaptureAtkUnitManager

---

FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs

The other offsets below are probably also broken, but I don't know exactly what they are used for to test that.

Fix some ActionTimelineManager offsets

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs

Following the talks about accurate representation of client internals, I'm wondering if these functions can be included.
However, my use case is that I use SetPosition to position a BNpc I spawned on the character select screen (summoner pet/scholar fairy). 🙂
Up to you guys, if you want to include it or not.

Add Rotate and SetPosition to GameObject

---

FFXIVClientStructs/FFXIV/Client/Game/MJI/IslandState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIManager.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIPastureHandler.cs
ida/data.yml

Title says it all. First pass, let's see how it goes.

First Pass of MJIManager for 6.5

---

FFXIVClientStructs/FFXIV/Client/Game/MJI/IslandState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIFarmState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIPastureHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

- Rename MJIFarmHandler > MJIFarmState (file only, class name was correct)
- Add new fields to MJIFarmState
- Add LayoutId to GameObject
- Make MJIFarmPasture explicit to mitigate cexporter issue

More MJI changes

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
ida/data.yml

This function enables/disables Main Commands. What else is there to say?!

Add AgentHUD.SetMainCommandEnabledState

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs

@pohky, you merged my PR while I was editing the xmldoc. (No biggie, how should you know!) 😅
Since English isn't my native language I received some help from ChatGPT an DeepL. 🤓

Better docs on ReassignGearsetId

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs

This is a slightly nicer way of setting a Macro icon since it computes the correct MacroRowIconId for you.

Add Macro.SetIcon

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

- Add `ReloadMacroSlots()` method to `RaptureHotbarModule` (thanks @grittyfrog!)
- Adds some other related reload/delete methods
- Updates saved hotbar information and provides some extra findings

Hotbar Research

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/PronounModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureTextModule.cs
ida/data.yml

This PR adds the following functions:
- `RaptureTextModule.ProcessMacroCode`
- `PronounModule.ProcessString`

Add text processing functions

---

FFXIVClientStructs/FFXIV/Client/Game/GcArmyManager.cs
ida/data.yml

Some data about Grand Company Squadrons.

Add GcArmyManager

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs

Adds `RidingPillion` as a new value for `CharacterModes`

add mount passenger CharacterMode

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs

This PR adds the Doman Enclave Reconstruction Reclamation Box to the `InventoryType` enum.
The name is based on agent `ReconstructionBuyback`.

Add InventoryType.ReconstructionBuyback

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentBase.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentDropDownList.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentList.cs
ida/data.yml

It is what it is (a mess, as usual).

Update AtkComponentList, AtkComponentDropDownList

---

FFXIVClientStructs/STD/String.cs

This mainly adds a conversion from `StdString` to `ReadOnlySpan<byte>`.
Also uses it as an optimization for `GetBytes()` and `ToString()` when the string is < 2 GiB.
When it's ≥ 2 GiB (even if I do not think it should ever happen in practice):
- `ToString()` would have thrown anyway as `Encoding.GetString(byte[])` attempts to use the 32-bit length of the array ;
- `GetBytes()` falls back to `Buffer.MemoryCopy` instead of copying that amount of data one byte at a time.

Add StdString.AsSpan

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
ida/data.yml

Sigs for some GameObject setup stuff related to companions (Minions, Mounts, Ornaments etc).

Some GameObject setup sigs

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Demihuman.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Human.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Monster.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Weapon.cs

Includes a breaking change, discussed with Pohky on #plugin-dev.

Decal and FC crest fields and accessors

---

ida/CExporter/CExporter.csproj
ida/CExporter/Exporter.cs
ida/CExporter/Extensions.cs

Updates the CExporter to use .NET 8 function pointer logic.

Net 8 CExporter

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkCollisionNode.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs

Somehow my comments on #691 were ignored by everyone. 😕
If this is wrong, then please explain it to me.

Fix function signatures added with #691

---

FFXIVClientStructs/FFXIV/Client/Graphics/Scene/EnvScene.cs

This is an array of weather IDs supported by the environment.

Add WeatherIds to EnvScene

---

FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIFarmState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIFavorState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIGranariesState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIManager.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIPastureHandler.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJIAnimalManagement.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJICraftSchedule.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJIDisposeShop.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJIFarmManagement.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJIGatheringHouse.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJINekomimiRequest.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

That's the same as https://github.com/aers/FFXIVClientStructs/pull/664, rebased to 6.51 hotfix. Unfortunately, I messed up with github UI, resulting in previous PR being auto closed.

Some research for MJI related stuff.

---

ida/data.yml

Very quick pass based on a 1.2.5 DLL I got somewhere. Should be accurate enough for troubleshooting purposes at least (c.f. PDBs).

Add a couple zlib names to data.yml

---

FFXIVClientStructs/FFXIV/Common/Component/BGCollision/BGCollisionModule.cs
FFXIVClientStructs/FFXIV/Common/Component/BGCollision/Collider.cs
FFXIVClientStructs/FFXIV/Common/Component/BGCollision/Mesh.cs
FFXIVClientStructs/FFXIV/Common/Component/BGCollision/Object.cs
FFXIVClientStructs/FFXIV/Common/Component/BGCollision/Quadtree.cs
FFXIVClientStructs/FFXIV/Common/Component/BGCollision/Resource.cs
FFXIVClientStructs/FFXIV/Common/Component/BGCollision/Scene.cs
FFXIVClientStructs/FFXIV/Common/Math/AABB.cs
FFXIVClientStructs/FFXIV/Common/Math/Matrix4x3.cs
FFXIVClientStructs/FFXIV/Common/Math/Vector3.cs
ida/data.yml

Most of the game's collision module. Some missing parts that I didn't reverse much:
- resource manager, resource handle etc.
- non-pcb meshes that don't seem to actually be used ('simple' mesh that is built by a function that seems to have no callers, 'legacy pcb' mesh that have old version in the header)

Collision research.

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Hotbar.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

I swear one day we will know everything about this class. Using `internal` to mark things I'm not completely sure about yet.

Filling out RaptureHotbarModule

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
ida/data.yml

Add more fucntions to Utf8String

Utf8String Functions

---

FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Device.cs
FFXIVClientStructs/FFXIV/Client/System/File/FileAccessPath.cs
FFXIVClientStructs/FFXIV/Client/System/File/FileDescriptor.cs
FFXIVClientStructs/FFXIV/Client/System/File/FileManager.cs
FFXIVClientStructs/FFXIV/Client/System/File/FileThread.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/CursorManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/EnvironmentManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/GameWindow.cs
FFXIVClientStructs/FFXIV/Client/System/Input/Cursor.cs
FFXIVClientStructs/FFXIV/Client/System/Threading/Thread.cs
FFXIVClientStructs/FFXIV/Client/System/Threading/ThreadManager.cs
FFXIVClientStructs/FFXIV/Common/Configuration/ConfigBase.cs
ida/data.yml

I would appreciate someone really looking this over (especially for typos and accidental api breakage)
Adds following classes
- ThreadManager
- Cursor
- GameWindow *
- File-Manager/-Thread-AccessPath
\* Acknowledgements:
- GameWindow is a completely assumed name and most likely is a much more low-level class

Extend Framework

---

FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/ContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentDirector.cs
ida/data.yml

Adds:
- `GetContentTimeMax` function to `ContentDirector`
- `ContentTimeMax` field to `InstanceContentDirector` and `PublicContentDirector`
- `PublicContentDirectorType` to `PublicContentDirector`

Content director updates

---

FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentDirector.cs
ida/data.yml

The fields were added in #749 two hours ago, so this shouldn't be a breaking change.

Fix PublicContentDirector

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RecipeFavoriteModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This module stores favorite recipes in a `RCFAV.DAT`.

Add RecipeFavoriteModule

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemContextCustomizeModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This module stores the Inventory Subcommand Settings in `ITCC.DAT`.
There is some more data after those arrays, but I'm too lazy to find out what it is. Sorry.
At least the struct is added. 🤷‍♂️

Add ItemContextCustomizeModule

---

FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBLM.cs

Not sure how I goofed this one up, bleh. Breaking change I suppose, but the fields are so new I would be shocked if anyone else is using them yet.

Correction to AddonJobHudBLM.cs

---

ida/data.yml

- Frequently referenced in mod-related crashes, would like to include in PDB.

Add method name for ReadSqpkChunk

---

FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/PVShader.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/PixelShader.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/ShaderPackage.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/VertexShader.cs

VertexShader and PixelShader structures

---

ida/data.yml

Update data.yml (Component::Text::Localize::Noun)

---

FFXIVClientStructs/Attributes/FixedArrayAttribute.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Inspect.cs

`FixedArrayAttribute` doesn't seem to be used anywhere and I fell into the trap of using it instead of `FixedSizeArrayAttribute`.

Obsolete FixedArrayAttribute

---

FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsNote.cs

See [discord message](https://canary.discord.com/channels/581875019861328007/653504487352303619/1203713141830193212)
Size increased for both DIsplayID and DisplayStatus to 19 items each

Increase ContentsNote size for 19 item arrays

---

FFXIVClientStructs/FFXIV/Component/Text/MacroDecoder.cs
FFXIVClientStructs/FFXIV/Component/Text/TextModule.cs
FFXIVClientStructs/FFXIV/Component/Text/TextParameter.cs
ida/data.yml

I've been reading PlayerParameters (gnum/gstr) from GlobalParameters with success.
Now all we need is a way to make StdDeques ourselves, so we can pass local parameters to FormatString. 😅

Add TextParameter

---

FFXIVClientStructs/FFXIV/Client/System/Input/SoftKeyboardDeviceInterface.cs

API compat breaking, I know. Unsure why/how anyone else would have been using this, however.

Fix SoftKeyboardDeviceInterface return types

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Common/TimePoint.cs
ida/data.yml

The TimePoint is used throughout the whole application and from all the context I have is most likely not from std::chrono but SE made, which to my knowledge was the recommended way to do this at the time the client was created.
Name and namespace wise I appreciate feedback

Framework: Time struct and frame delta details

---

FFXIVClientStructs/FFXIV/Client/Game/Event/GoldSaucerDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/GoldSaucer/GFateDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/GoldSaucer/GoldSaucerManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

Not sure about namespaces, I took inspiration from existing ones.
Should we even add unused ctors that got inlined in the data.yml? I imagine that the update script will do weird stuff with those.
Anyway, I haven't spent too much time on it (which is why there are a couple internal fields), so... more discoveries as they come, I guess. 🙂

Add GoldSaucer manager and directors

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs

We have the `ChangeUiMode` method, that sets it, but not the field to check it. :/

Add RaptureAtkModule.UiMode field

---

FFXIVClientStructs/FFXIV/Client/Game/Event/CraftEventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventFramework.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandlerModule.cs

Implements `Client::Game::Event::CraftEventHandler` (name taken from the old RTTI dump)

Add CraftEventHandler

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs

I blame those AgentHUD MapMarkers for being there.

Move MiniMapGatheringMarkers to AgentMap

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/System/Input/TextService.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureTextModule.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkColorDataManager.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkExternalInterface.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

🤔
- I wasn't sure if `Component::GUI::AtkFontAnalyzer` inherits all those classes or not, so I left them out.. okay, but also because I didn't want to compare them right now.
- Regarding `InventoryItem.Spiritbond`: Past self ([#plugin-dev](https://discord.com/channels/581875019861328007/653504487352303619/1210528041646817280)) made this discovery and didn't make a note. ._. So here it is! Someone else figure out what to do now. :joy:

Random additions

---

FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentBozja.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentEureka.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Inspect.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

Diff excluding `AgentId format cleanup`: ab8d85ab920aa31d88d68b1ce6cff9f75c0560cc...3225956d9b3ada65498fdc88447530a5d01be505
---
First day(s) in Eureka... 🙃
Not really sure about the Excel stuff and the inheritance of `Client::Game::InstanceContent::DynamicEvent`.
I tried to find some more references, so it makes more sense.

Add PublicContentEureka and PublicContentBozja (and more)

---

ida/data.yml

Just adds the data.yml definition so at least IDA Rename includes names

Add AddonPartyMemberList

---

FFXIVClientStructs/FFXIV/Client/Game/Event/Director.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs
ida/data.yml

Add AgentMap.EventMarkers

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/DataCenterHelper.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/WorldHelper.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This PR adds UIModule vfs:
- 27: GetDataCenterHelper
- 28: GetWorldHelper

Add DataCenterHelper and WorldHelper

---

.github/workflows/pr-breaking-change-check.yaml

I added action logic to remove the label when no breaking change was found anymore.
This is untested, but please give it a try!

Update breaking change check action

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventSceneModule.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventSceneTaskInterface.cs
ida/data.yml

I don't know what I'm doing. 
A couple names are made up based on the lua functions.
Maybe I should clarify that the GroupPoseTasks vector contains CreateAppearance tasks for GPose.

Update EventSceneModule, add EventSceneModuleTaskManager

---

ida/data.yml

I tried to give things a more uniform name based on newer managers.
Also I added a couple new managers. Most of them don't exist in the old exe so I made up names based on lua functions they are used in or what sheets they interact with. 😅
Hope that is alright?

Update Managers (data.yml)

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentPartyMember.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyPartyInvite.cs
ida/data.yml

Sigs taken from <https://github.com/Infiziert90/ChatTwo/blob/main/ChatTwo/GameFunctions/Party.cs#L11>

Add AgentPartyMember and add functions to InfoProxyPartyInvite

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentChatLog.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCrossWorldLinkShellList.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyLinkShell.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/AcquaintanceModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

All sigs taken from <https://github.com/Infiziert90/ChatTwo/blob/main/ChatTwo/GameFunctions/Chat.cs#L29>
This those not include the print/send functions for tell messages

Add multiple chat related functions and offsets

---

FFXIVClientStructs/FFXIV/Client/Game/ReconstructionBoxManager.cs

Refactored the struct so it returns itself using `isPointer: true` on `StaticAddressAttribute`.

Refactor ReconstructionBoxManager

---

FFXIVClientStructs/FFXIV/Client/Graphics/Physics/BoneSimulator.cs

A few more fields I found that are somewhat useful, I guess

Yet more bone simulator fields

---

FFXIVClientStructs/FFXIV/Client/Game/UI/MarkingController.cs
ida/data.yml

Sig taken from <https://github.com/Infiziert90/WaymarkPresetPlugin/blob/main/WaymarkPresetPlugin/MemoryHandler.cs#L64>

Add func to place waymark presets

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkUnitManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

~~We can do Addons!~~ Maybe not. Without uld nothing gets drawn, even if you attach a custom AtkResNode, because the AtkResourceRendererManager is missing and all that stuff.

Creatable AtkUnitBase

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs

Fix static mistake

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInspect.cs
ida/data.yml

Sig taken from <https://github.com/Caraxi/SimpleTweaksPlugin/pull/730/files#diff-39a32d7ab590a8aeb29eb263ec88452317cb7a9e7b4b2e058d299c8a3b8b7387R20>

Add ReceiveSearchComment func

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs

[Dawntrail] Fix build after merging main

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs

For https://github.com/goatcorp/Dalamud/pull/1834#discussion_r1641929453

Add AtkUnitBase VirtualTable

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentAetherCurrent.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCompanyCraftMaterial.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCountDownSettingDialog.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCraftActionSimulator.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentScenarioTree.cs

I forgot to add `[Agent(AgentId.AetherCurrent)]` on AgentAetherCurrent.

Add AgentAttribute on AgentAetherCurrent

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkValue.cs

Based on helper from @MidoriKami: https://discord.com/channels/581875019861328007/1246473943548825730/1253413305230557290
Untested. Please have a look!

Add AtkValue.ToString() overload

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs

I did this last week. It's a start.

[Dawntrail] Partially update UIState, PlayerState

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs

For the data.yml, a new SetStain function was added at `E8 ?? ?? ?? ?? 0F B6 53 1D`

[Dawntrail] Update Client::Game::InventoryItem

---

FFXIVClientStructs/FFXIV/Client/UI/AddonItemSearch.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemSearch.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRecipeNote.cs

Adding some things from the [Fast Search tweak](https://github.com/Caraxi/SimpleTweaksPlugin/blob/1.9.6.0/Tweaks/UiAdjustment/FastSearch.cs) can it can be updated for APIX (https://github.com/Caraxi/SimpleTweaksPlugin/pull/736).

ItemSearch structs for the Fast Search tweak

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerInterface.cs

Adding the attribute to correctly generate the FixedSizeArray _characters.

Add GenerateInterop to AgentBannerInterface.Storage

---

FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/MountContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/Group/GroupManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Group/PartyMember.cs
FFXIVClientStructs/FFXIV/Client/Game/StatusManager.cs
FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutWorld.cs
FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentDeepDungeonInspect.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJIAnimalManagement.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRetainerTask.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCrossRealm.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyFreeCompany.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaView.cs
ida/data.yml

Not sure if I've done it right tho.

More EntityId and FixedSizeArray conversions

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyItemSearch.cs

Spotted this during benchmark already.
Absolutely not sure though!

Fix ProcessItemHistory arguments

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGaugeEnums.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

Implementation of Pictomancer gauge at level 80. Will require updates as more mechanics are unlocked.

Add Pictomancer gauge

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionCross.cs

Correction in AddonActionCross

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
ida/data.yml

- Address in yml
- Signature in QuestManager.cs

Fix GetBeastTribeAllowance

---

FFXIVClientStructs/FFXIV/Client/UI/AddonAetherCurrent.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonCharacter.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonCharacterClass.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonFateProgress.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonMiragePrismPrismBox.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentAetherCurrent.cs
FFXIVClientStructs/FFXIV/Client/UI/UIInputData.cs

Also updating some UIInputData offsets I need (technically only MouseWheel but eh).

Update some Addons I need

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCommonList.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyFriendList.cs

CharacterData received 8 more bytes of currently unknown

Update InfoProxyFriendlist & InfoProxyCommonList

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs

Commented out NumAcceptedLeveQuests because I was unable to find it anywhere, and NumAcceptedQuests is weird.

Updated QuestManager field offsets.

---

FFXIVClientStructs/FFXIV/Client/Game/Character/BattleChara.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/CastInfo.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/ForayInfo.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/TimelineContainer.cs
ida/data.yml

Some breaking changes fresh off the press!

Update Character, BattleChara

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs

Fix AgentContext.TargetObjectId offset

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarBase.cs
ida/data.yml

They inserted a new vf at 73. Everything afterwards shifted by 1.
fixes #992

Fix AddonActionBarBase vfuncs

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModuleInterface.cs

I think they are just temporarily stored there, so I named it QueuedBattleTalks.
Also, ShowBattleTalkImage was missing 2 arguments.

Add QueuedBattleTalks to AgentHud

---

FFXIVClientStructs/FFXIV/Client/UI/AddonCharacter.cs

Fix AddonCharacter PreviewCollisionNode

---

FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs

- Renamed TellId to ContentId, as thats what it is
- Renamed the unknown function parameter to reason, as it writes to 0x10BA
- Shifted all offsets for the additional accountIds
- Added accountId to all functions

Update RaptureShellModule offsets and functions

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentChatLog.cs

- 0x8 shift happend after LinkedItem
- New field LinkedItemQuality
- New fields for Linkshells names in the chat selector
- New field ContextStatusName

Update agent chat log

---

FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterUtility.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Demihuman.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Human.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Monster.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Weapon.cs

Fix CharacterBase and subclass sizes and offsets for 7.0

---

ida/ffxiv_idarename.py
ida/ffxiv_structimporter.py

I doubt anyone can test this but it seems to work on my machine. Will eventually add structimporter support when I have the motivation.

idarename, structimporter: Add Binary Ninja support

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
ida/data.yml

Originally PR'd to Dalamud by @Small-Miao (https://github.com/goatcorp/Dalamud/pull/1918).
Slightly edited in hope they don't add yellow/orange as warning, lol. 😜

Add RaptureAtkModule.ShowTextGimmickHint

---

FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudACN.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudAST.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBLM.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBRD.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudDNC.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudDRG.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudDRK.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudGNB.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudMCH.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudMNK.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudNIN.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudPCT.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudPLD.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudRDM.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudRPR.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudSAM.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudSGE.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudVPR.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudWAR.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudWHM.cs
ida/data.yml

- Documented the new/altered job gauge addons and their substructs
- Broke out the various `_prerequisites` arrays into specifically named fields

JobHud Addons updated in full for 7.0

---

FFXIVClientStructs/FFXIV/Client/Game/Control/EmoteController.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentEmote.cs
ida/data.yml

Example code that executes the Wave emote:
```cs
using var disabled = ImRaii.Disabled(!AgentEmote.Instance()->CanUseEmote(16));
if (ImGui.Button("Execute Emote"))
{
var playEmoteOption = new EmoteController.PlayEmoteOption
{
TargetId = TargetSystem.Instance()->GetTargetObjectId()
};
AgentEmote.Instance()->ExecuteEmote(16, &playEmoteOption);
}
if (ImGui.Button("Execute Emote (without log message)"))
{
var playEmoteOption = new EmoteController.PlayEmoteOption
{
TargetId = TargetSystem.Instance()->GetTargetObjectId(),
Flags = 1
};
AgentEmote.Instance()->ExecuteEmote(16, &playEmoteOption);
}
```

Add AgentEmote

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGaugeEnums.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

I'm assuming the FieldOffset is correct. If it is, this is how that field gets used to determine what Serpent's Tail does.

Add SerpentCombo to ViperGauge

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

FFXIVClientStructs.FFXIV.Client.Game.Gauge.SummonerGauge.Attunement change

change SummonerGauge

---

FFXIVClientStructs/FFXIV/Client/UI/AddonContentsFinder.cs

I'm certain SelectionRadioButton is fixed, but I am just assuming the other two also shifted by the same amount.

ContentsFinder

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/HousingObject.cs
FFXIVClientStructs/FFXIV/Client/Game/RetainerManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonBuddy.cs
FFXIVClientStructs/FFXIV/Component/Text/MacroDecoder.cs
ida/data.yml

- Add UIState.RequestResetTimestamps()
- Add UIState.GetNextChallengeLogResetTimestamp()
- Add UIState fields NextMapAllowanceTimestamp and NextChallengeLogResetTimestamp
- Fix AddonBuddy.RadioButtons offset
- Add RetainerManager.RequestVenturesTimers()
- data.yml updates
- TODO comments for wrong types
- and more

Various additions and fixes

---

FFXIVClientStructs/FFXIV/Client/Game/Event/CraftEventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/Group/PartyMember.cs
FFXIVClientStructs/FFXIV/Client/Game/TitleController.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/TitleList.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonAreaMap.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonNamePlate.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismMiragePlate.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs
FFXIVClientStructs/FFXIV/Component/Text/MacroDecoder.cs
ida/data.yml

Stuff you find when you have debug tools...
Bot 100% sure about `Client::Game::Character::BlacklistProxyContainer`, but it seems to have some connections to a Blacklist provider. I think it's for hiding companions/mounts of players that are blacklisted. So I guess this kinda makes sense. 🤔 I only added it to the data.yml for now, as it's enough to have the title update function in TitleController.

Various fixes and additions

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Base/CutSceneController.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Base/LinkedList.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Resource/SchedulerResource.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/ScheduleManagement.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonImage.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentStatus.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/AcquaintanceModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureTextModule.cs
ida/data.yml

- **Added:** Character.IsWanderer/IsTraveler/IsVoyager functions
- **Added:** CharacterModes.Dead (found in IsDead vfunc)
- **Added:** Comments on some PlayerState fields, so devs know which sheets/columns to use as index
- **Added:** Scheduler LinkedList to access CutSceneControllers
- **Fixed:** Missing string property generation for SchedulerResource.ResourceName.Buffer
- **Fixed:** AcquaintanceModule.Acquaintance struct got bigger because AccountId was added
- **Fixed:** AgentStatus.CharaView offset
- **Fixed:** AddonImage AddonAttribute names were not correctly splitted
- **Fixed:** Instance getter of ScheduleManagement didn't resolve the pointer

Fixes and additions

---

ida/data.yml

Gave some more AtkResNode functions a name.

AtkResNode data.yml updates

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/ActionEffectHandler.cs
ida/data.yml

- function to determine extra param for summons
- fields for ballista mode
- some misc functions in data.yml

Some more actionmanager functions and fields

---

FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

**GameObject:**
- Add vf46 `GetCenterPosition`: This function returns the center point of a game object, be it a character or furnishing.
- Add vf69 `IntersectsRay`: This function returns whether a ray intersects with the game object. If character or furnishing, it will check for intersection with the model, otherwise, it will check against the game object's approximate center position.
Example for IntersectsRay:
```cs
var camera = Control.Instance()->CameraManager.GetActiveCamera();
if (camera == null)
return;
var mousePos = ImGui.GetMousePos();
var ray = new Ray();
camera->SceneCamera.ScreenPointToRay(&ray, (int)mousePos.X, (int)mousePos.Y);
var hitPosition = new Vector3();
var modelChecked = false;
var hit = gameObject->IntersectsRay(&ray, &hitPosition, &modelChecked);
// if hit == …
```

Update GameObject, DrawDataContainer

---

FFXIVClientStructs/FFXIV/Client/Game/Fate/FateContext.cs

Copied from Dalamud: https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/ClientState/Fates/FateState.cs

Add FateState enum

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs

Those are probably going to shift with 7.1 but at least we have comments to find them again!

Fix AgentLobby.IsLoggedIn

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs

With this Destroy and Tick can be hooked in Dalamud without scanning for their sig.

Add VTable and VFuncs to Framework

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Client/System/Input/InputData.cs
FFXIVClientStructs/FFXIV/Client/UI/UIInputData.cs
ida/data.yml

Started working on this a bit, but didn't fully commit. :P

Split UIInputData into input structs

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/AchievementListModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/AcquaintanceModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/AddonConfig.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/AozNoteModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/BannerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/EmoteHistoryModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/FieldMarkerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/FlagStatusModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/GoldSaucerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/GroupPoseModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemContextCustomizeModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemFinderModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemOrderModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/MinionListModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/MountListModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/PvpSetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureUiDataModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RecipeFavoriteModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RetainerCommentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/UserFileManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/VVDActionModule.cs

UserFileEvent got bigger by 0x8, mass-adjusting offsets.

Mass-update UserFileEvents

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBar.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarX.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonActionCross.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonActionDoubleCrossBase.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudACN.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudAST.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBLM.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBRD.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudDNC.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudDRG.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudDRK.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudGNB.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudMCH.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudMNK.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudNIN.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudPCT.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudPLD.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudRDM.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudRPR.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudSAM.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudSGE.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudVPR.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudWAR.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudWHM.cs

Same approach as #1157 ; offsets updated, but sizes _not_ yet updated.

Mass-update more Addons

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/Material.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/Model.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Human.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ModelResourceHandle.cs

human +0x40 across the board
material texture entry move handle
modelresourcehandle +0x20
+ added mask values to model

Material, model and human 7.1 fixes

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventFramework.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs

- Something was added after EventFramework.EventSceneModule, shifting things.
- Updated IsLoggedIn in AgentLobby for a Dalamud PR (also very easy to find). Didn't bother with the rest yet.

Update EventFramework, AgentLobby.IsLoggedIn

---

FFXIVClientStructs/FFXIV/Client/UI/AddonMiniTalk.cs

very fast, probably wrong research done for Khayle.

add chat bubbles

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/AddonConfig.cs

Update AddonConfig CurrentHudLayout offset.

Update AddonConfig CurrentHudLayout offset.

---

FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDeepDungeon.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDirector.cs

Not sure if these are fully correct for deepdungeon

update some instance content offsets

---

FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentOceanFishing.cs

Everything's shifted by 0x50 in the directors glhf

Fixes for InstanceContentOceanFishing

---

FFXIVClientStructs/FFXIV/Client/Game/SatisfactionSupplyManager.cs

A new Custom Deliveries NPC was added.

Partially update SatisfactionSupplyManager

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemDetail.cs

Add vtable to AgentItemDetail

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
ida/data.yml

Fix InventoryItem

---

FFXIVClientStructs/FFXIV/Client/UI/UIModuleInterface.cs

https://discord.com/channels/581875019861328007/1246473943548825730/1307765694699667457

Restore int returns on UIModules Rotate* vfs

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs

It returns a bool, used at 0x14028D44B

Fix AgentLobby.UpdateCharaSelectDisplay return value

---

FFXIVClientStructs/FFXIV/Client/Game/BGMSystem.cs
ida/data.yml

I just don't know any further, so I added a bunch of stuff as private and comments instead. 🤷‍♂️
Probably good to have those function names and a bit of a struct though.

Add partial BGMSystem

---

ida/data.yml

data.yml RSF additions

---

FFXIVClientStructs.ResolverTester/Program.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

Have to take some extra care about those bitmasks now with these helpers. There is no function to sig for this.

Fix CaughtSpearfishBitmask offset and add IsFishCaught, IsSpearfishCaught

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Inspect.cs

Fix Inspect offsets

---

FFXIVClientStructs/FFXIV/Application/Network/NetworkModule.cs
ida/ffxiv_structs.yml

Also has a second commit with types for some fields where I am not exactly sure what they are used for, but I find having the type still makes things less messy in ida.

Fix `NetworkModule` offsets

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/BGInstancingRenderer.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/BaseRenderer.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/Manager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/ModelRenderer.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/PostBoneDeformerBaseUpdater.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/ShaderManager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/TerrainRenderer.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/VerticalFogRenderer.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/WaterRenderer.cs
ida/data.yml

I have no freaking idea what I'm looking at. 🤷‍♂️
Hope the Views array length change doesn't break something somewhere.

Add some placeholder Render::Manager structs

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/System/Input/InputDevice.cs
FFXIVClientStructs/FFXIV/Client/System/Input/InputDeviceManager.cs
FFXIVClientStructs/FFXIV/Client/System/Input/KeyboardDevice.cs
FFXIVClientStructs/FFXIV/Client/System/Input/KeyboardDeviceInterface.cs
FFXIVClientStructs/FFXIV/Client/System/Input/MouseDevice.cs
FFXIVClientStructs/FFXIV/Client/System/Input/MouseDeviceInterface.cs
FFXIVClientStructs/FFXIV/Client/System/Input/PadDevice.cs
FFXIVClientStructs/FFXIV/Client/System/Input/PadDeviceInterface.cs
FFXIVClientStructs/FFXIV/Client/System/Input/RepeatCounter.cs
FFXIVClientStructs/FFXIV/Client/System/Input/VibrationControl.cs
ida/data.yml

Don't know what's going on there. Just wanted to map the classes.
And found the SetVibration function in a plugin, so I thought I'll add that at least.

Add InputDeviceManager

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyItemSearch.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs

Breaking change technically, but its broken anyway so I guess its fine

Update Signatures for 7.16

---

FFXIVClientStructs/FFXIV/Client/Game/Character/TimelineContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentBozja.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentDirector.cs

That's what happens when you don't have a generator for this shit. :P

Update sheet data

---

FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
FFXIVClientStructs/FFXIV/Component/Text/TextModule.cs
ida/data.yml

Update data.yml and some other small things

---

FFXIVClientStructs/FFXIV/Component/Completion/CategoryData.cs
FFXIVClientStructs/FFXIV/Component/Completion/CompletionModule.cs
FFXIVClientStructs/FFXIV/Component/Completion/CompletionModuleInterface.cs
FFXIVClientStructs/FFXIV/Component/Text/TextModule.cs
FFXIVClientStructs/FFXIV/Component/Text/TextModuleInterface.cs
ida/data.yml

Fix CompletionModule

---

ida/data.yml

- PreBoneDeformerResourceHandle is actually KineDriverResourceHandle.
- Added missing classes.

Fix ResourceHandle addresses

---

FFXIVClientStructs/FFXIV/Client/Game/NameCache.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

Was addding what we found about InventoryItem stuff back when, landed in AgentItemDetail (Tooltip stuff), found a NameCache and decided to reverse it. 🤷‍♂️

Add NameCache

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/Game/RetainerManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEventData.cs
ida/data.yml

It's really not worth to do single PRs for these changes.

Various changes

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/PartialSkeleton.cs
ida/ffxiv_fullrun_ida.py

Size is still the same (0x230, see 140479B1D).

Fix PartialSkeleton offsets

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/Skeleton.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Attach.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/BgObject.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Terrain.cs
FFXIVClientStructs/FFXIV/Client/LayoutEngine/Layer/BgPartsLayoutInstance.cs
FFXIVClientStructs/FFXIV/Client/LayoutEngine/Terrain/TerrainManager.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ModelResourceHandle.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/SharedGroupResourceHandle.cs

- add attach
- some basic resource handles
- update ModelResourceHandle fields for 7.2
- add attach related fields to skeleton

7.2 & attach stuff

---

FFXIVClientStructs/FFXIV/Client/UI/AddonCabinetWithdraw.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonMiragePrismPrismBox.cs

- Adds the CabinetWithdraw addon
- Fixes offsets for MiragePrismPrismBox

Add CabinetWithdraw and fix offsets for MiragePrismPrismBox

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs

Appears to be a generic field that some addons use for storage

Add param field to AtkUnitBase

---

FFXIVClientStructs/FFXIV/Client/UI/AddonAreaMap.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonNamePlate.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/ActionBarNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/AreaMapNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/CastBarNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/CastBarStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/Hud2NumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/InventoryNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/LetterNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/NamePlateNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/PartyListNumberArray.cs

Added a couple Data Arrays and moved old ones into the new UI/Arrays folder

Added Data Arrays

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryItem.cs

Fix InventoryItem.EqualTo

---

FFXIVClientStructs/FFXIV/Client/Game/Fate/FateContext.cs

FateRuleEx is set at 1416493C6
Music is set at 14164946D
both WORD

Swap FateContext.Music with FateRuleEx

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

Fix AtkUnitBase.GetWindowBounds vf index

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

Checked until it matched again (at Update).

Fix more AtkUnitBase vfs

---

FFXIVClientStructs/FFXIV/Client/UI/Arrays/BlackListNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/BlackListStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/Common/SocialListMemberNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/Common/SocialListMemberStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/CrossWorldSyncshellStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/FreeCompanyMemberNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/FreeCompanyMemberStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/FriendListNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/FriendListStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/GearSetListStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/HudNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/HudStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/InventoryNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/LetterNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/LetterStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/PartyMemberListNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/PartyMemberListStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/SocialListNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/SocialListStringArray.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkArrayData.cs

Mapped quite a lot more arrays c:

More Arrays

---

FFXIVClientStructs/FFXIV/Client/Game/ChocoboTaxiManager.cs
ida/data.yml

Add ChocoboTaxiManager

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs

Update InventoryManager (Trade stuff)

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentActionDetail.cs

This resolved to the Addon instead of the Agent...

Fix AgentActionDetail VTable sig

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentBase.cs

The delta frame time is passed to `AtkComponentBase.OnUldUpdate`.

Fix AtkComponentBase.OnUldUpdate args

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/ShaderManager.cs

We were thinking about showing the number of Shader Packages loaded while the game is compiling them in Dalamud.
See https://discord.com/channels/581875019861328007/860813266468732938/1361828391388450829

Add ShaderPackageResourceHandles to ShaderManager

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

Fix CaughtFishBitmask length

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentTelepotTown.cs

Add AetheryteCount to AgentTelepotTown

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMcGuffin.cs
ida/data.yml

Adds functions to check if a McGuffin can be opened, and to open a specific McGuffin.

Add AgentMcGuffin functions

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRecipeNote.cs

SelectedRecipeCategoryPage:
0 - Level-based Recipes; 1 - Special Recipes; 2 - Master Recipes
SelectedRecipeCategory:
0 - 19: Level-based Recipes (Current Level 1 - 100)
Above 1000: Special Recipes and Master Recipes

Add SelectedRecipeCategory and SelectedRecipeCategoryPage to AgentRecipeNote

---

FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterManagerInterface.cs
FFXIVClientStructs/FFXIV/Client/Game/Group/GroupManager.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSManager.cs
FFXIVClientStructs/FFXIV/Client/Game/WKSCosmoManager.cs
ida/data.yml

Some prep. 🚀🌕👀🛠️🤖
It's like MJIManager with a bunch of structs handling different things. Someone can map that out in the future, I guess.

Add WKSManager

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryItem.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/UiSavePackModule.cs

Fix vf numbering in InventoryItem and UiSavePackModule

---

FFXIVClientStructs/FFXIV/Component/Completion/CategoryData.cs
FFXIVClientStructs/FFXIV/Component/Completion/CompletionModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkTextInput.cs
ida/data.yml

Define the parts of the completion system needed to implement autocompleted commands in dalamud

Add parts of the Completion system

---

FFXIVClientStructs/FFXIV/Client/Game/Event/CraftEventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSManager.cs

**Added:**
- `WKSManager.FishingBait` (refs: `140CF72E0`, `140D107F7`)
- `CraftEventHandler.WKSClassLevels`/`WKSClassJobs` from https://github.com/WorkingRobot/Craftimizer/blob/main/Craftimizer/Utils/CSCraftEventHandler.cs with fixed type (refs: `140CF9640`, `140CF96D0`, `140CF9730`)

Add WKS findings

---

FFXIVClientStructs/FFXIV/Client/Game/Fate/FateContext.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSManager.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSMechaEvent.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSMechaEventMapMarker.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSMechaEventModule.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSMechaEventStageHandlerBase.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSModuleBase.cs
ida/data.yml

Struct handling Mecha Events stuff.
Lots of data in a struct starting at 0x70, probably for all the objects that spawn and stuff. Didn't touch that.
I just want to move on.

Add WKSMechaEventModule

---

ida/data.yml

- Added EurekaStoryProgressManager.
- Removed Lua functions that don't make sense (their a1 is `Common::Lua::LuaState*`).
- Fixed some things.

data.yml update

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
ida/data.yml

Had these changes laying around.

Update InventoryManager, EventHandler

---

FFXIVClientStructs/FFXIV/Client/Game/HwdManager.cs
ida/data.yml

Fix HwdManager.Instance

---

FFXIVClientStructs/FFXIV/Client/UI/AddonToDoList.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/ToDoListNumberArray.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/ToDoListStringArray.cs
FFXIVClientStructs/FFXIV/Client/UI/ListPanel.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

Reversed most of AddonToDoList's structure and arrays
It uses ListPanel, so worked that out, too.
Also introduces names for a few AtkUnitBase vfuncs

Add AddonToDoList, ListPanel, and arrays for _ToDoList

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs
ida/ffxiv_structs.yml

didn't know what to call this. Occult Counter (pmonk) uses this field as does Haymaker L in eureka

ActionManager "proc timers"

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInterface.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModuleInterface.cs
ida/data.yml

Just some Callback/ReceiveEvent stuff.

Update AtkModule handlers

---

FFXIVClientStructs/FFXIV/Client/System/Memory/IMemorySpace.cs

Add IMemorySpace.Calloc/Realloc/Recalloc

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

Add GetClassJobLevel to PlayerState

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/RenderTargetManager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/SubView.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/View.cs
ida/data.yml

Update Render-related structs

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkTextNode.cs

This is what peak form looks like

Update AtkTextNode TextFlags

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs

Not 100% sure, but those that I can test seem to work.

Update unlock bitmask sizes

---

FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs

Some wrong things just look the part.

Fix offsets in CharacterBase for 7.3

---

FFXIVClientStructs/FFXIV/Client/Game/Event/BattleLeveDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/Director.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/LeveDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/ContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Buddy.cs
FFXIVClientStructs/FFXIV/Client/UI/UIGlobals.cs
ida/data.yml

Well, one of them.
Updated for and verified on current patch, of course.

Clearing out my git stash

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs

The GetNameplateWorldPosition function from the other PR made me want to look into this more. 🙃

Add some GameObject fields

---

FFXIVClientStructs/FFXIV/Client/Game/UI/RecipeNote.cs

no idea why I bikeshedded these changes for half a year lol

Upstream some old Craftimizer changes

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentAlarm.cs
ida/data.yml

Add AgentAlarm

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/WorldHelper.cs

sometimes it's more convenient than looking up in lumina sheets so

Add WorldHelper functions

---

ida/data.yml

Hand in collectable items to shop

Add HandIn to AgentCollectablesShop in data.yml

---

FFXIVClientStructs/FFXIV/Client/UI/AddonArmouryBoard.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentInputBase.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentTextInput.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkInputManager.cs

Adds functions that are already in data.yml

AtkInputManager

---

FFXIVClientStructs/FFXIV/Client/Game/Event/Director.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/MassivePcContent/MassivePcContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/DirectorTodo.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/MassivePcContentTodo.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/UI/Arrays/ToDoListNumberArray.cs
ida/data.yml

Update Todo stuff
