Component/GUI/AtkComponentBase.cs
Component/GUI/AtkResNode.cs
Component/GUI/ULD/ULDComponentInfo.cs
Component/GUI/ULD/ULDObjectInfo.cs

When the ULD objects were moved, ComponentType got deleted for some reason. I still use it in my UIDebug fork, so I know it works at least for my purposes. 
Also, lets make the Structs contain the enum rather than the raw value. if we're going to compare it anyways, just save a step.
Although ComponentType might be a short instead of an int, dunno.

NodeType and ComponentType,

---

FFXIV/Client/Graphics/Matrix44.cs
FFXIV/Client/UI/AddonNamePlate.cs
FFXIV/Client/UI/AddonTalk.cs
FFXIVClientStructs.csproj
STD/NoExportAttribute.cs
ida/CExporter/Program.cs
ida/README.md
ida/data.yml
ida/ffxiv_client_structs_arrays.h
ida/ffxiv_idarename.py

Handle generics by creating \<GenericType\>::\<ImplentingType\>. For example, PointerVector::BoneSimulator.
Handle stupid union issues by just not exporting things. See Matrix44. 
Implement bytearray gap strategy, fill with byte[] instead of sequential longs. Makes importing to ida a breeze. Different strokes for different folks.
Rolling in ida script fix to this PR after collaborating with @pohky

Update for C header export

---

FFXIV/Client/UI/Addon.cs
FFXIV/Client/UI/AddonChatLogPanel.cs

A request or something
A way to label structs with what addons they apply to would be nice
this is purely for debugging purposes really, would allow automatic identification and easy parsing of addon data
Only added to ChatLogPanel for now because cbf adding it to them all if you hate the idea

Add AddonAttribute

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

From Dalamud API3, offsets listed below are -8 
```        /// <summary>
/// Gets the amount of Aetherflow stacks available.
/// </summary>
[FieldOffset(2)]
public byte NumAetherflowStacks;
/// <summary>
/// Gets the current level of the Fairy Gauge.
/// </summary>
[FieldOffset(3)]
public byte FairyGaugeAmount;
/// <summary>
/// Gets the Seraph time remaining in milliseconds.
/// </summary>
[FieldOffset(4)]
public short SeraphTimer;
/// <summary>
/// Gets the last dismissed fairy.
/// </summary>
[FieldOffset(6)]
public DismissedFairy DismissedFairy;```

Scholar guage, seraph timer offset is wrong.

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/ConfigModule.cs

I have no idea where does offset for values come from.
+0xC0 to match change in code: this+0x5718+arr[stuff] => this+0x57d8+arr[stuff] in SetOption()

updated config module offsets

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

Paradox is a new thing BLM has when swapping between Umbral and Astral stances.
It seems like they reused the Enochian value to track this state.
Also Enochian != 0 doesn't mean enochian is active now, since Enochian == 2 means its not up but Paradox is active.

Fixing BLM Enochian

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

- Added the new Firstminds' Focus count.
- Renamed Botd to Lotd since Blood of the Dragon is baseline now and these values only track Life of the Dragon now.

Update dragoon gauge

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs

This represents the character ID (same as in the `FFXIV_CHR*` folder names) of the currently previewed character on the character select screen.

add SelectedCharacterId offset to AgentLobby

---

FFXIVClientStructs/FFXIV/Client/UI/AddonPartyList.cs

couldn't get Trust2, and Trust6 would get a chocobo. Noticed that index of Trust6 goes over the size of a struct, so there is an obvious erroneous offset

erroneous offset in TrustMembers

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs

not sure how to call that flags since they aren't the only ones that control visibility 🤷 
i use them to show addons only on mouseover
```c#
[Flags]
public enum AddonVisibility : byte
{
UserHidden = 1 << 0, // Hidden by the user in current HUD layout
GameHidden = 1 << 2 // Hidden by the game, Scenario Guide during duty for example
}
```

Add AtkUnitBase VisibilityFlags

---

FFXIVClientStructs/FFXIV/Common/Lua/LuaState.cs
ida/data.yml

Filled in a bit more of the LUA-related API. The `CallMemberFunction` variants go up to 26, but that seemed unnecessary to document.

Additional Lua Updates

---

FFXIVClientStructs.Generators/FunctionGenerator/FunctionModels.cs
FFXIVClientStructs.Generators/FunctionGenerator/FunctionSyntaxContextReceiver.cs
FFXIVClientStructs.Generators/FunctionGenerator/FunctionTemplates.cs
FFXIVClientStructs/Attributes/MemberFunctionAttribute.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

PR because its changing the generator
Adds ability to make member functions private, with an example of its usage

Private MemberFunction

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs

This commit (hopefully) provides some useful information on the RaptureHotbarModule, specifically HotBarSlot and the fields contained therein. It also adds a few found member functions to RaptureHotbarModule and derivatives that came up in creating XIVDeck.
I'm unsure about a lot of these things, but they _look_ correct based on observations and game testing. A lot of things appear to be overloaded on the hotbars, so I'm unsure how much we can realistically find.

Add notes on RaptureHotbarModule, new fields

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

- Add some more HotbarSlot functions, especially those related to a few of our unknowns.
- Additional documentation on some fields.
Of note: I'm putting in some names into ClientStructs only that refer to our "unknowns" in the hotbar struct. I don't _like_ committing in unknowns, but it may help someone else trying to hunt for something.
I also feel semi-confident about refactoring a few of the `HotbarSlot` fields, assuming approval is given:
- `UNK_0xCA` to `CostType`
- `UNK_0xCB` to `CostDisplayMode`
- `UNK_0xD0` to `Cost`  (n.b. this is overloading with items where it's quantity)
- `UNK_0xD4` to `RecipeItemId`
- `UNK_0xD8` to `RecipeCraftType`
- `UNK_0xDC` to `RecipeValid`
- `UNK_0xDD` to `IsRecipe`
A few things are still mysteries though:
- `UNK_0xC4` is... something. Some uses split …

More hotbar research!

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarBase.cs

This PR seeks to add the following fields:
- **`0x238` - `CurrentPulsingSlots`**  
This field is a `WORD` that lists all currently pulsing hotbar slots as a bitmask. Written to by `PulseActionBarSlot` and possibly others.
- **`0x23C` - `RaptureHotbarId`**  
This field is a byte (!) that denotes the `RaptureHotbarModule` hotbar ID that this ActionBar is currently referencing. This field will change in response to cycles on `_ActionBar` or `_ActionCross`, but is also present on fixed hotbar slots. There is some oddness in the value of this field for WXHB slots presently, but this may be a limitation/misunderstanding of `RaptureHotbarModule` as well.
- **`0x240` - `IsSharedHotbar`**
This field is set to `01` when the currently-viewed hotbar is "shared", and `00` otherwise. What this value …

Add Discovered AddonActionBarBase Fields

---

ida/data.yml

Just adds some functions that I know what they do to the list.
Also, yes SE has 2 different `SurveyDuration` calculations so renamed one to say which one it is from.
For patch `2022.06.21.0000.0000` if I'm not done before patch drop

Add submarine and airship functions names

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Cabinet.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

This pull request seeks to add a bit of research done regarding various unlock systems in the game. The vast majority of these methods (and supporting information) was found from `IsItemActionUnlocked` and spreads from there. With this pull request, I think most (all?) unlockable item types now have associated ClientStruct entries.
Of particular note that may need closer review:
- I added a struct for `Cabinet` (the in-game Armoire). Because there appear to be a number of member functions for dealing with the armoire, it seemed prudent to combine all of these together. The size 0x45 is a best guess, but it may be 0x44 instead.
- I added a new field to `UIState` for `UnlockedCompanionsBitmask`. Unlike `Cabinet`, I was not able to find anything specific to this mask, so I decided to keep it …

Add Unlock Research

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

This commit purely consists of some fixups of some potentially-problematic signatures that may break. Thanks to Aers and Pohky for catching these and informing me about them.
The IsMcGuffinUnlocked signature relied on a few offsets remaining stable, which probably won't happen, but no point in tempting fate.
The IsFramersKitUnlocked signature had a hardcoded 0x28 in it, which would have broken upon SE adding a new Framer's Kit, so the signature has been extended a bit.

Fix some potentially unstable sigs in PlayerState

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs

- New offset, documented the name and stable-sig
Please double-check my math before merging, the math checks out but I'm unable at present to test this on live code.
```
g_Client::Game::UI::UnlockedCompanionsMask - 0x14207CDC2
g_Client::Game::UI::UIState_Instance       - 0x142066360
--------------------------------------------------------
0x000016A62
```
If there's a way I can use our sig for this, that would be awesome, but honestly not sure how.

Fix UnlockedCompanionsBitmask in UIState

---

FFXIVClientStructs/FFXIV/Client/UI/AddonPartyList.cs

The offset for EmnityByte was 8 bytes off.
There's likely more properties that are shifted but I could only test this one.

Fixing offset for EmnityByte in PartyListMemberStruct

---

FFXIVClientStructs/FFXIV/Client/Game/MJIManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

Add in a few more discovered fields, as well as the bulk (I hope) of Island Sanctuary agents. The vtbls should be right, but yaknow. I'm not *completely* sure about the behavior of `LockedPouchItems` either, but it's been consistent with those findings as of now.
This commit also fixes a stray tab because Aireil threatened me.

Island Sanctuary Agents and Manager Fields

---

FFXIVClientStructs/FFXIV/Client/Game/MJIManager.cs

(Was going to keep this as a draft until more fields were resolved, but the added `PlaceId` field probably gives it enough utility to open the PR at this point)
Additional details:
- Filled in by calls to `ffxiv_dx11.exe+C99000` in a few different events. (Opening workshop agenda, etc)
- `MJIBuildingPlacement+8` values match for the same building types.
- There appears to be landmark-related values following `Cabin`, but the structure seems off.

MJIManager Building Fields

---

FFXIVClientStructs/FFXIV/Client/Game/Camera.cs

This is the "smoothed" camera distance when zooming in and out.

Add interpolated camera distance

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs

This is used in cutscenes and GPose to override EorzeaTime. When the flag is true, it effects the time absolutely, when false it appears to be some kind of offset to real EorzeaTime.

Add EorzeaTimeOverride to Framework.

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

An itty-bitty pre-6.3 PR for some Unlock Link array things.
Specifically:
- Add a reference to UnlockLinkBitmask to UIState
- Update some documentation around the (still cryptic) `IsUnlockLinkUnlockedOrQuestCompleted` method
- Add an address for `SetUnlockLinkValue` to data.yml.
Detailed notes about IULUOQC are in the actual commit itself; there are still unfortunately some unanswered questions about that.

Add some Unlock Link Array things

---

FFXIVClientStructs.InteropSourceGenerators/CStrOverloadsGenerator.cs

this 2nd pr is actually your fault because you merged too fast. it's not my fault

fix for multiple overload param names

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs

It seems the offsets at the end of the struct moved by 2 bytes.

Fix AgentMap offsets

---

FFXIVClientStructs/FFXIV/Client/UI/UI3DModule.cs

Fix offset of `NamePlateObjectInfoPointerArray` and `NamePlateObjectInfoCounter`
Thanks to Banana Bread for finding them!

Fix a few offsets in UI3DModule

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGatheringNote.cs
ida/data.yml

Based on AgentRecipeNote
It doesn't seem this function requires the add 0x10_000 that RecipeNote requires.
~~I don't know how to build ClientStructs so I hope this works =x~~
I think I managed to get it to build? It really didn't like the syntax until it was built.

Add AgentGatheringNote

---

FFXIVClientStructs.sln
ida/CExporter/CExporter.csproj
ida/CExporter/Program.cs
ida/ffxiv_client_structs_arrays.h
ida/ffxiv_client_structs_arrays_ghidra.h

Updated the CExporter utility based on the array-gen branch:
- Added new output files that are able to be successfully imported by Ghidra
-- Ghidra had issues with the :: format as well as struct members with shorter type names (mostly enums)
- Updated CExporter project to target .NET 7
- Updated existing headers to newest ClientStructs data

Update CExporter Utility & Add Ghidra Compatible Array Headers

---

FFXIVClientStructs/FFXIV/Client/Game/UI/MobHunt.cs

Mistakenly used `FixedArray` instead of `FixedSizeArray` property.
Is the field okay to be a `fixed int[]` or does it need to be a `fixed byte[]`?

Fix Wrong Attribute for MobHunt

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandler.cs

Found on events attached to B, A and S Rank monsters.

Add MobHunt to EventHandlerType

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

Not sure on the name, because it could also mean the player is subscribed to the Premium Service Plan as a whole.
As far as I can see it's only being used as a bool in combination with a check for InventoryType.PremiumSaddleBag1 (4100).
Setting it to true makes the right saddlebag appear. 😏
Currently located at 0x1420EA1EB (updated Feb. 9, still at +133 from PlayerState).

Add HasPremiumSaddlebag to PlayerState

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
ida/data.yml

The static function `PlayerState.GetBeastTribeAllowance()` is misplaced because the passed private `GetBeastTribeAllowancePointer()` is actually `QuestManager_GetSingleton()`.
I have added it as a member function to QuestManager and marked `PlayerState.GetBeastTribeAllowance()` as obsolete.

Move GetBeastTribeAllowance to QuestManager

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkArrayDataHolder.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
ida/data.yml

Adds native getters to AtkArrayDataHolder and AtkModule to get NumberArrayData*, StringArrayData* and ExtendArrayData* by index. If the requested ArrayData is empty, it will allocate it before returning.
The AtkModule virtual functions simply forward the call to the respective AtkArrayDataHolder member function.

Add ArrayData getters

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
ida/data.yml

PlayerState contains Wondrous Tails data, also known as Weekly Bonus or Weekly Bingo internally.
Since the sheet and addon use the name WeeklyBingo, we settled on that one in the Discord. 🙂

Add WeeklyBingo to PlayerState

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PvPProfile.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

These are the stats used by the PvP-Profile window.
I used the last field as a hint for the size.
There are also some ushort fields at 0x14, 0x16, 0x18, 0x1A and 0x1C and a byte at 0x52 that are being set via ProcessActorControlPacket (or rather methods used in there), but I couldn't figure out what they were used for, so I left them out.

Add PvPProfile to UIState

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
ida/data.yml

- Added `NumLeveAllowances` field to provide the number of leve allowances the player has.
- Added `IsLevequestComplete(ushort levequestId)` to check if a specific levequest has been completed.
- Added `GetNextLeveAllowancesTimestamp()` which provides the player's next leve allowance timestamp.
Since it needs to be multiplied by 60 in order to become a unix timestamp, I've made it private and added the following two public helper methods:
- `GetNextLeveAllowancesUnixTimestamp()` provides a unix timestamp.
- `GetNextLeveAllowancesDateTime()` provides a local DateTime.

Add levequest methods to QuestManager

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
ida/data.yml

Not all of the `WeeklyBonus` names where properly changed to `WeeklyBingo`, this PR fixes those.

Fix WeeklyBingo names

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs

The constructor for QuestManager does allocate the last element at 0xEE0 size of 0x8, the next sequential struct is allocated at 0xF10 from QuestManager start.
I've been using the value at 0xEF8 in DailyDuty for quite some time, it's the number of currently accepted levequests.

Improve QuestManager

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRecipeNote.cs

This field is just a uint on AgentRecipeNote I found that contains the recipe id of whichever recipe the player has started actively crafting. Contains 0 when not crafting or just looking at the recipe list (RecipeNote). Surprisingly does not contain the `0x10_000` that the "internal" APIs otherwise do.

Add "ActiveCraftRecipeId" field to AgentRecipeNote.

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs

Note, this function will return -1 if the timers window has not been opened yet this session.
In DailyDuty I do this by waiting for the ContentsInfo addon to be non-null.

Add TreasureMap Member to UIState

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFishGuide.cs
ida/data.yml

This PR adds a function to open the Fish Guide for a given Item Id.
Since the Fish Guide is split into two lists, one for fishing and one for spearfishing (the toggle button is below the item list), the caller has to specify which list the item is listed in using the `isSpearfishing` parameter.
All it needs is a check against the SpearfishingItem sheet:
```cs
var isSpearfishing = Service.Data.GetExcelSheet<SpearfishingItem>().Any(row => row.Item.Row == itemId);
```

Add AgentFishGuide

---

ida/CExporter/Program.cs

This adresses the following three problems:
* When a generic type was part of FFXIVClientstructs namespace, the type name was corrupted
* Nested types in generic types had the same name as their parent
* Pointers to generic types would be resolved to either void* or an invalid System type
I have tested these cahnges with Ghidra only, as I don't have IDA. If someone could test this with IDA it would be appreciated

CExporter: Correctly handle generic types

---

FFXIVClientStructs/FFXIV/Client/UI/AddonContentsFinder.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs

This does rename `SelectedContentFinderCondition` to `SelectedDutyId`, as this hasn't been merged into dalamud yet, this is probably fine.

Improve AgentContentsFinder & AddonContentsFinder

---

FFXIVClientStructs/FFXIV/Application/Network/WorkDefinitions/LeveWork.cs

Sequence is not the second byte of the LeveId. It comes after the LeveId. Just like in [QuestWork](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Application/Network/WorkDefinitions/QuestWork.cs).
Happy little accidents.

Fix LeveWork Sequence

---

FFXIVClientStructs/FFXIV/Client/Game/MJI/IslandState.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIManager.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIPastureHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

- Adds some extra `IslandState` data, specifically:
- Whether the player has the ability to interact with the island (`CanEditIsland`)
- Whether the Pasture is currently under mammet care (`PastureUnderCare`)
- The daily fees for both pasture and farm care (`PastureDailyCareFee` and `FarmDailyCareFee`)
- Rename `IsFunctionLocked` to `IsFunctionUnlocked` as I got behavior backwards
- Add information about minions to `MJIPastureHandler` (this name may be a misnomer now?)
- The `RoamingMinions` array tracks which minions are currently released and roaming the Sanctuary
- The `MinionSlots` array tracks specific minions and other data (like position, ObjectId, etc.)
- Some other sneaky fixes

Even More Island Sanctuary Findings

---

FFXIVClientStructs/FFXIV/Client/Game/SatisfactionSupplyManager.cs

I'm not smooth enough brain to figure out what the correct offset should be for the old sig, so I just found another sig that is easier to figure out.
The old address resolves to 2-bytes before the actual struct

Fix bad sig, offset to wrong location

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemOrderModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs

This adds a struct for `Client::UI::Misc::ItemOrderModule`.
I was just interested in whether an item sorter is currently busy sorting during a frame (which comes down to checking `SortFunctionIndex >= 0`).
Other than that, I tried my best to make sense of it. Eventually I gave up on finding out how it works in detail.
Depends on #359 (UserFileEvent)

Add ItemOrderModule

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/RouletteController.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs
ida/data.yml

Some notes:
The length of `PSNOnlineID` was taken from Sapphire's [ServerZoneDef.h](https://github.com/SapphireServer/Sapphire/blob/ffdbed7/src/common/Network/PacketDef/Zone/ServerZoneDef.h#L908). Apparently the ID is a maximum of 16 characters long, so I guess the 17th byte is for the null terminator.
`PlayerState.PenaltyTimestamps` is used by `RouletteController.GetPenaltyRemainingInMinutes`, which I also have added. It's used by `AgentContentsFinder`, so I added the fields there too. Don't know what the second penalty timestamp is used for.
`FishingBait` was at the wrong offset.
Also I couldn't figure out index 1 for `SelectedPoses` or what `NoviceNetworkFlag.Unknown14` checks. Maybe someone else knows more.
`NumOwnedMounts` is incremented at `0x14090DD5F` while reading in the mount …

More PlayerState research

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkArrayData.cs
FFXIVClientStructs/FFXIV/Component/GUI/NumberArrayData.cs
FFXIVClientStructs/FFXIV/Component/GUI/StringArrayData.cs
ida/data.yml

This PR adds a native SetValue method for NumberArrayData and changes the one for StringArrayData.
The SetValue function for StringArrayData we used was actually the one called SetValueForced in data.yml.
I replaced it with the one that's actually SetValue, which has a convenient feature:
If the `managed` parameter is set to true, the game will allocate it's own memory for the text of the passed byte* to make a copy of it. It's then fully managed by SetValue itself, since it stores a copy of the new pointer in a ManagedStringArray and will reuse or reallocate it as needed. This allows us to use `[GenerateCStrOverloads]` to simply call SetValue with a C# string.
Since the arguments have changed I marked this as a breaking change. Maybe this is something for the next API level increase.

[Breaking Change] Add native ArrayData SetValue methods

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkEvent.cs

Changing the underlying type of the `AtkEventType` enum to byte allows us to use it directly as type for the field `Type`.

[Breaking Change] Change AtkEventType type

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemOrderModule.cs

- Fixed offset for `ItemOrderModule.ActiveRetainerId`
- Removed `ItemOrderModuleSorter.UnkItemsArray`, which had the same FieldOffset as `PreviousOrderArray`. Based on the position I probably just didn't see it's the first element of the vector.

Small fixes to ItemOrderModule

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
ida/data.yml

This is only used in 4 places, 3 of them in SelectYesNo, and the last is in a helper that's presumably used by the "return to starting point" box

Add GetAsAtkHoldButton

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs
ida/data.yml

Since `AtkStage_GetNumberArrayData` exists in data.yml, I thought I'd look around and see what I could find.
- Added:
- GetStringArrayData
- GetExtendArrayData and
- a pointer to the whole AtkArrayDataHolder.
- Renamed the existing `GetSingleton1` to just `GetSingleton` and found a second one which I called `GetSingleton2`.
- Capitalized the address of `RemoveAllEvents` and sorted the functions by address.

Add AtkArrayDataHolder to AtkStage

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs

There's another sig that's collided but I don't know which one it is supposed to be:
FFXIVClientStructs\FFXIVClientStructs\FFXIV\Common\Component\BGCollision\BGCollisionModule.cs: Multiple matches for `48 83 EC 48 48 8B 05 ?? ?? ?? ?? 4D 8B D1`

Fix GetPositionShort sig collision

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs

TempMapMarker size has increased by 8 byte, causing everything after them to shift by 60 byte. 
Have not checked if TempMapMarker data is at the same offsets because neither constructor of it changed in any way.

Update AgentMap offsets.

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Control/Control.cs
FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

Updated offsets for:
- UIState.cs
- Character.cs (partial)
- I just wanted to fix OnlineStatus and rearranged the offsets while doing so. Not sure what StatusEffectVFXId is, but at that offset is now TitleID. Maybe it moved to 0x1E0?
- Control.cs
- I guess TargetSystem grew (didn't check).
- QuestManager.cs
- PlayerState.cs (missed one)
Updated data.yml:
- Removed SetConditionByPermissionAndLog
- I added this a while ago, but it doesn't set the condition at all. I think it checks them against the permissions and prints the error, if it doesn't match. Anyway, I didn't look much into it, just wanted it to be removed since it has a wrong name.
- Fixed a typo in a comment (gearsetIndext -> gearsetIndex)
- Trimmed whitespaces

Various offset updates

---

ida/data.yml

Partly named due to find under `Client::Game::JobGaugeManager_Update` which calls `**a1 + 24` and all `vf_3` does almost the same as `Init` but only for setting from the packet

Update JobGuage data.yml vf_3 name

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
ida/data.yml

This can be helpful because the setter also triggers a redraw.

Add X/Y getter and setter to AtkResNode

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs

- Explicitly denotes `Character.GetCastInfo()` as possibly returning null
- Perform null check in `Character.IsCasting`
Fixes ObjectTable bug in Dalamud.

Fixes Character.IsCasting flag for Companions et al.

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

I saw commit daa76a0 (sorry for that btw) and thought the sizes might be old now too. So here's an updated with some more bitmasks. 🙂
- I reduced the size of `UnlockLinkBitmask`, so it fits until `UnlockedAetherytesBitmask` starts. I hope this doesn't cause any problems.
- It looks like there is 1 byte padding between `UnlockedAetherytesBitmask` and `UnlockedHowToBitmask`?! I'm not sure if `UnlockedAetherytesBitmask` is just 1 byte too short now or not, but I tested `IsAetheryteUnlocked` against the Aetheryte sheet and it works fine. 🤷‍♂️
- Fun fact: I also rented a Chocobo for the first time to check if `IsHowToUnlocked` works. It works. 😄👍
Oh yeah, and I renamed `UpdatePlayerAetheryteList` to `UpdateAetheryteList` in the data.yml, so it aligns with the method in Telepo.cs.

Update unlock bitmasks in UIState

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentChatLog.cs

return value of InsertTextCommandParam seems to be unused from every caller
the bool arg doesn't seem to effect the text param being inserted into the chat box.
This function does not automatically send anything to the client, it only puts markers into the chat box:
ie: <flag>

Add AgentChatLog

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGatheringNote.cs

Adds struct for getting gathering area information

AgentGatheringNote add GatheringAreaInfo

---

ida/data.yml

Signature `E8 ?? ?? ?? ?? 49 8B 04 ?? 80 A3` in [DrawDataContainer.cs](https://github.com/aers/FFXIVClientStructs/blob/c2fb96f/FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs#L61) is correct, but the address in data.yml is wrong:

Fix DrawDataContainer.HideHeadgear in data.yml

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/AcquaintanceModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/UserFileManager/UserFileEvent.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This is a breaking change, because it's changing the type in UIModule.
There is more in there, for example another array of 3 Acquaintances at 0xE50, but I have no idea whats that for.

Add AcquaintanceModule

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs

- `FromString(string)`: Switched to lamda expression.
- `FromString(string, IMemorySpace*)`: Simplify the SetString call, as the null terminator is already added inside CStrOverloads ([see generator](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs.InteropSourceGenerators/CStrOverloadsGenerator.cs#L99-L104)).

Simplify Utf8String

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs
FFXIVClientStructs/FFXIV/Client/Game/GameMain.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

- Adds `UIModule#IsInGPose` at UIModule vf77
- Adds static (probably) method `GameMain.IsInGPose`
- Adds relevant data.yml findings
- Adds `UIModule#IsInIdleCam` at UIModule vf80 (found by @Haselnussbomber)
- Adds static method `GameMain.IsInIdleCam`
- Adds relevant data.yml findings
And, as as bonus:
- Adds `ActionManager.GetDutyActionId`
- Found as a static member of ActionManager (thanks @MidoriKami)
- Adds relevant data.yml findings

Add GPose, IdleCam Checks

---

FFXIVClientStructs/FFXIV/Client/Game/Fate/FateContext.cs

These fields shifted by 64 bytes since someone checked them last.
Also adds `IsExpBonus` field

Fix FateContext Offsets

---

FFXIVClientStructs/FFXIV/Client/UI/AddonNeedGreed.cs

Also fixed incorrect size, determined from dtor
Marked internal struct as obsolete
Provides features for https://github.com/Caraxi/SimpleTweaksPlugin/pull/608

AddonNeedGreed More members

---

FFXIVClientStructs/Interop/Address.cs
FFXIVClientStructs/Interop/Resolver.cs

I came across an edge case where the resolver only resolved a signature once, even though it was present multiple times with different offsets.
I have identified two reasons behind this issue:
1) The key used in the `_textCache` dictionary did not account for the offset of a `StaticAddress`.
2) The loop was prematurely broken when an `Address` had been resolved at the given location, disregarding any other Addresses.
This would happen for the following example, in which the VTableAddress has the same sig (with an offset) as the Ctor method (without offset):
```cs
[VTableAddress("E8 ?? ?? ?? ?? 48 8B F0 48 89 45 0F", 0x1C)]
[StructLayout(LayoutKind.Explicit, Size = 0x90)]
public unsafe partial struct LuaCutsceneState
{
[FieldOffset(0x10)] public Utf8String Path;
[FieldOffset(0x78)] public …
```

Fix not resolving same sig with different offsets

---

FFXIVClientStructs.InteropSourceGenerators/StaticAddressGenerator.cs
FFXIVClientStructs.InteropSourceGenerators/VTableAddressGenerator.cs

This PR makes `StaticAddressPointers` a partial class.
Otherwise we can't have both the `StaticAddress()` attribute on functions inside the struct and the `VTableAddress()` attribute on the struct.

Partial StaticAddressPointers

---

FFXIVClientStructs.ResolverTester/Program.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs

- Add HotBars as a FixedSizeArray to replace HotBar.
- Add friendly fields StandardHotBars and CrossHotBars. These don't exist in the game's code (probably), but exist to make devs happy.
- Add PetHotBar and PetCrossHotBar for pet actions, roleplay, and similar.
- Add ScratchSlot, used for temporary memory operations.
- Add docs to HotBarSlot#Set to prevent future confusion for people

Clean up HotBar references, add discovered fields

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismMiragePlate.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismPrismBox.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs

Implements the missing `MiragePrismMiragePlate` agent.
This is my first PR here; let me know if anything needs changing.

Implement AgentMiragePrismMiragePlate

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs

There are two new data structures used and implemented here, one is based on a LinkedList, the other is based on a Map, neither a AtkLinkedListnor a StdMap properly fit here, as the "CurrentSize" field of a map is always zero for these, and the list implementation used here doesn't include size information once you are at the Start and End pointers.
SimpleMapMarkerContainer only contains basic information about the map marker, icon id, location, and lumina row id for whatever kind of entry it is.
For example: 
In this image there are 2 entries for CustomTalk, these are the "The Smith" markers near Bentbranch.
MapMarkerContainer contains the very useful data, locations, tooltips, and much more.
Each marker in the map has a vector of additional markers. The markers contained in that vector …

Add Map Marker Data to UI::Map

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs

PR #500 added a `LinkedList` struct to the `FFXIVClientStructs.FFXIV.Client.Game.UI` namespace.
I think this could cause some confusion and would rather see it being nested inside the `MapMarkerContainer` struct.

Nest LinkedList

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

- Corrects PlayerTargetObjectID to LookTargetId, add docs
- Corrects TargetObjectID to HardTargetId, add docs
- Adds SoftTargetId
- Corrects GetTargetId to GetHardTargetId, add docs
- Adds GetSoftTargetId
- Adds SetHardTargetId, SetSoftTargetId
- Allows implicit casting GameObjectID to/from a ulong

Add soft target to Character

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs

`RaptureAtkUnitManager.IsUiVisible` doesn't exist and the setter function `SetUiVisibility`, which does more than setting the flag, is a vf of `RaptureAtkModule`, so we can't easily move it into `RaptureAtkUnitManager` anyway.

Remove Obsolete from RaptureAtkModule.IsUiVisible

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentDragDrop.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentListItemRenderer.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkDragDropInterface.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkDragDropManager.cs

AtkDragDropInterface is a previously missed base class that's implemented by AtkComponentDragDrop and AtkComponentListRenderer. This PR was made because AtkDragDropManager holds pointers to these interfaces, and that struct has been updated with new fields, too.

Add AtkDragDropInterface & AtkDragDropManager

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemOrderModule.cs
FFXIVClientStructs/STD/Pair.cs

- Updated ItemOrderModule.RetainerSorter to the correct type. Breaking change, but the code was inherently broken, anyway.
- ItemOrderModuleSorter had an incorrect size (and an undocumented bool).
- Deprecates ItemCount and SortFunctionCount because they already had easy accessors.
- Snuck in a Deconstruct method for StdPair so they can be used like C# tuples.

Update ItemOrderModule and Sorters

---

FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/Game/RetainerManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRetainerList.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RetainerCommentModule.cs

This PR removes structs that are no longer necessary because of FixedSizeArrays, and some obsolete fields that may have been part of the cleanup in #556.
Not included are:
- `RaptureHotbarModule`, because Kaz left a comment waiting for "better fixed arrays".
- `RaptureGearsetModule` (handled by #562).
- `RaptureMacroModule` (handled by #504).
Also fixed `RetainerCommentModule` and removed the Comment property in favour of a cleaner fixed byte array (since the offset and size was wrong, I assume nobody used it anyway).

FixedSizeArray cleanup

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs

I forgot to remove this when changing to FixedSizeArray. Sorry.

Remove unneccessary RaptureGearsetModule.Gearsets

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Data/CharacterData.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Achievement.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterUtility.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Base/SchedulerState.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Resource/SchedulerResource.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Resource/SchedulerResourceManagement.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerInterface.cs

This PR changes all `VTable` fields to be named `vtbl` instead.
`VTable` should be handled as a reserved name, because `VTable` is added by the [VirtualFunctionGenerator](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs.InteropSourceGenerators/VirtualFunctionGenerator.cs#L109).
If we do this now, with all the other breaking changes, we can add VirtualFunctions any time without breaking existing VTable fields, since they are called vtbl then. 😜

Rename VTable to vtbl

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs

Either IDA is failing me, or this sig is wrong.
annas sig_checker.py found it.

Fix InventoryManager.MoveItemSlot sig

---

FFXIVClientStructs/FFXIV/Client/Game/ActionManager.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonFieldMarker.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFieldMarker.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

- ActionType polish based on EXD name and correct values
- HotbarSlotType polish based on same
- Remove "waymark" everywhere
- Properly refer to it as `FieldMarker`
- Remove WaymarkIndex, as it's an EXD field

Update action names to match game internals

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs

(Breaking, figured I'd do one for API9)
AtkResNode's AddRGB fields are incorrectly labeled a ushort.
Example/Proof:

Fix AtkResNode AddRGB type

---

FFXIVClientStructs/Interop/Resolver.cs

The cache in the resolver currently uses code that potentially requires runtime reflection to serialize/deserialize the cache.
In theory this isn't compatible with trimming or AOT and produces warnings. 
Switching to the source code generation for System.Text.Json resolves this. See more at: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation
With this change, the project builds cleanly with no warnings when trimmed or publishing as part of an AOT project (and I've confirmed it actually functions when built and injected as a native library, at least on initial testing).

Don't use potential runtime reflection in Resolver

---

.gitattributes

There are `.png` files in this repo now (in [Ghidra/images](https://github.com/aers/FFXIVClientStructs/tree/main/Ghidra/images)), so git should handle them as binary files.
Alternatively, they could be uploaded with GitHubs editor (just drag the images into the markdown), so they aren’t in the repo at all. 🤷‍♂️

Add binary attribute for .png files

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterSetup.cs

Not really sure what to call this.
These methods moved into this sub struct, calling on character will cause a crash.
Also not sure if we want to obsolete these?

Fix CopyFromCharacter and SetupBNpc (Add CharacterSetup struct)

---

FFXIVClientStructs/FFXIV/Client/UI/AddonSalvageItemSelector.cs

New to this so may have missed some other changes here, but these new offsets seem correct to me.

Fix AddonSalvageItemSelector offsets

---

FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/ShaderPackage.cs

This fixes offsets in `ShaderPackage` for 6.5, adds the fields that caused the offset shifts, and also adds `ConstantSamplerUnknown.Size`

Fix ShaderPackage for 6.5

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarCross.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonActionDoubleCrossBase.cs

Field offsets I've been using for a while to get the state of the Cross Hotbar. Also threw in the `AddonActionCross.Selected` field to summarize the selection state via enum.

Add field offsets/descriptions for AddonActionCross and AddonActionDoubleCrossBase

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarBase.cs

This address is a pointer to the component, whose ownernode is the node for the entire slot.

AddonActionbarX Slot, add ComponentDragDrop

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
ida/data.yml

This PR adds two functions:
- `RaptureGearsetModule.ReassignGearsetId`, which swaps two gearsets positions in the list
- `RaptureHotbarModule.ReassignGearsetId` updates links to the gearsets on the hotbars accordingly.

Add ReassignGearsetId

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
ida/data.yml

The counterpart to `AgentHUD.SetMainCommandEnabledState`, added in #649.

Add AgentHUD.IsMainCommandEnabled

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs

This PR adds `RaptureAtkModule.AgentUpdateFlag`, which is (in most cases) set in packet handlers and checked in agents (although some agents set them too).
I'm not 100% sure on all names, especially `NameplateUpdate`, but I tried to make the most sense of them based on where they are used.
As an example, these flags are set when I open and then close the retainer menu:
Earlier I tried out `UnlocksUpdate`, which was set after I unlocked an Orchestrion Roll. 👍
Also, `RaptureGearsetModule.ReassignGearsetId` (PR #646) is usually called before setting this flag to 2 (`ActionBarUpdate`), which is why I digged deeper on this.

Add RaptureAtkModule.AgentUpdateFlag

---

FFXIVClientStructs/FFXIV/Client/UI/UIInputData.cs

Fixes incorrect indexes for Numlock and Scroll. Those values work fine if the span is a `byte` span, however it's a span of KeyStateFlags' which are `ints`.
Adds VirtualKey enum, (taken from Dalamud, which was from `Defined in winuser.h from Windows SDK v6.1.`) and limited to the allowed range.
Added helpers for checking the keystates more easily. When I initially tried to use this module I was trying to compare the enum result to a specific state, and it doesn't work that way because they are flags, the helpers will alleviate that problem for others in the future.

UIInputData fixes and improvements

---

FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarCross.cs

- Added more offsets in `AddonActionCross`.
- Updated the size of `SavedHotBars` in `RaptureHotbarModule`. Patch 6.5 increased the size of this field from 61 to 65, making room for the upcoming 7.0 jobs.

Updates to Hotbar structs

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs

This moved by 4 bytes.
With all hotbars set to shared:

Fix HotbarShareStateBitmask offset for 6.5

---

ida/CExporter/Exporter.cs

I just wanted to import structs into IDA that I exported locally and got an error in IDA:
```
Error FFXIVClientStructs\ida\ffxiv_client_structs.h:3528: Variable 'HANGUL' has already been defined
Component::GUI::NodeType: failed to add constant Text=3 (0x3)
Total 1 errors
```
This happens because the new [`SeVirtualKey`](https://github.com/aers/FFXIVClientStructs/blob/6ab86ffe30f0d9939e7f0e0fcaa86b2e72f6cd9d/FFXIVClientStructs/FFXIV/Client/UI/UIInputData.cs#L166) enum has multiple entries with the same value, like:
```
KANA = 21,
HANGEUL = KANA,
HANGUL = KANA,
```
CExporter generates this, which makes IDA fail to import it:
```
HANGUL = 21,
HANGUL = 21,
HANGUL = 21,
```
I added a list that keeps track of processed values and skips duplicates.
Output with this fix is just
```
HANGUL = 21, …
```

[CExporter] Skip already processed enum values

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs

These "SimpleMapMarkerContainers" are actually StdDeques<SimpleMapMarker>
These Deques only have valid data during load, and otherwise have a size of zero. The only reason data still even exists there is because square doesn't clean it up.
I'm opting to remove these structs entirely as they are not particularly useful to start with. All the same data and more is available vis the MapMarkerContainers instead.

Remove Incorrect Map Structs

---

FFXIVClientStructs/STD/List.cs

Will be much more fleshed out with #666. I'm going off of naming by MSVC 11.0, but it should be identical until 2017/14.1. First element is at `Head->Next`, last element is at `Head->Prev`. The head pointer's value type is unused.

Add new StdList<T>

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkTexture.cs

The field `AtkTexture.TextureReady` was (accidentally?) [removed](https://github.com/aers/FFXIVClientStructs/pull/556/files#diff-b4de5d2de8a117307e2c6b2b3f960a2edba1e9da3b0a27bf57fe66f1f2f2fd5dL25) in #556.
I reintroduced it as obsolete with a comment to use the function instead.
The field contains the cached result of that function, which is why I added it as `private bool CachedIsTextureReady`, so it's in the CExporters structs.

Reintroduce TextureReady as obsolete

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs

According to code search, Mappy is the **only** plugin using these fields.
So once this updated ClientStructs is in Dalamud Stable and I am able to switch Mappy to the StdList<T> members, I will PR to remove the obsoletes and MapMarkerContainer structures.

UI::Map Use Correct Container

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

**Fixed:**
- Bitmask field sizes in both PlayerState and UIState were wrong
- My bad. They were one byte too short using `rowCount >> 3`. Now it uses `(rowCount + 7) >> 3` to round it up (this is equivalent to `Math.Ceiling(rowCount / 8)`).
- Offsets for Aetheryte ids were wrong and I fixed them, but...
**Bugged:**
- ...Aetheryte ids are ushort, not byte. Changing them would be a breaking change, so I opened a separate PR: #655
**Added:**
- `FreeAetherytePlayStationPlus` (not usable in Windows client)
- Fishing unlocks:
- `CaughtFishBitmask` and `CaughtSpearfishBitmask`, found via GatherBuddy signatures
- `UnlockedSpearfishingNotebookBitmask`
- Ornament unlocks:
- `UnlockedOrnamentsBitmask`
- Sightseeing Log unlocks:
- `UnlockedAdventureBitmask` and `UnlockedAdventureExPhaseBitmask` with …

More PlayerState/UIState findings

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCharaCard.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCommonList.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs

**AgentCharaCard:**
- Added a few fields
- Renamed `SearchComment1` to `SearchComment` (this one has resolved payloads/pronouns/whatever you call them)
- Renamed `SearchComment2` to `SearchCommentRaw` (this one has unresolved payloads/pronouns/whatever you call them)
- Updated type of the CharaView field to `CharaViewPortrait`
**AgentContentsFinder:**
- Offset fix in `ItemReward`
**AgentContext:**
- Offset fixes
- Replaced `ContextMenuTarget` with `InfoProxyCommonList.CharacterData`
-  Explanation: At 0x14023735C it calls `Client::UI::Info::InfoProxyCommonlist_SearchEntryByContenID` and sets the result (a pointer) to AgentContext+0xE08, which was of type `ContextMenuTarget*`. Just before that was a field of type `ContextMenuTarget` (no pointer). After I checked `InfoProxyCommonlist` and …

Update some structs

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkEvent.cs

(Updated with some suggested name revisions)
- Added event types 47 `DragDropBegin` and 50 `DragDropInsert`
- Obsoleted type 54 `DragDropUnk54`, to be replaced by `DragDropDiscard`
- Obsoleted type 55 `DragDropUnk55`, to be replaced by `DragDropCancel`
@MidoriKami  relevant to `AddonEventManager`.

Update AtkEventType enum

---

ida/CExporter/Extensions.cs

The [`StdVector<nint>`](https://github.com/aers/FFXIVClientStructs/blob/d00622e6e54bb8a625d8dcb3712da336766361cd/FFXIVClientStructs/FFXIV/Component/Text/MacroDecoder.cs#L5) in MacroDecoder gets exported as
```c
struct StdVector::SystemIntPtr /* Size=0x18 */
{
/* 0x00 */ System::IntPtr* First;
/* 0x08 */ System::IntPtr* Last;
/* 0x10 */ System::IntPtr* End;
};
```
but `System::IntPtr` itself is not defined. This causes errors when importing the structs file.
To solve this, I added the following entries to the FixTypeName function:
- `long*` or `nint*` to `__int64*`
- `ulong*` or `nuint*` to `unsigned __int64*`
- and, as a bonus, `nuint` to `unsigned __int64`

CExporter: Add support for int64 pointers

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

Agent names are made-up:
- **AgentFGSStageIntro** is used in `UIModule_ShowContentIntroduction`, which opens addons 842 (FGSStageDescription) and 843 (FGSStageIntroBanner). Data is set whenever loading screens in between stages are shown.
- **AgentFGSHud** seems to control the state of all the FGSHud* addons.
🤷‍♂️

Add missing Fall Guys addons/agents

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
FFXIVClientStructs/STD/String.cs

- Remove handling of ≥ 2 GiB strings in `StdString.GetBytes()` as it would not have worked anyway, as discussed ;
- Make `StdString.GetBytes()` `[Obsolete]` as discussed ;
- Change `Utf8String.Span` to `.AsSpan()` for consistency with the dotnet standard library (`.Span` stays, for now, with `[Obsolete]`) ;
- Add indexers with index and range to the two string structs ;
- Add an implicit cast from `Utf8String` to `ROS<byte>` ;
- Mark some members as `readonly`.
This is a followup to #702.

String stuff

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMacro.cs
ida/data.yml

Useful for the `OpenMacro` function which is the easiest way I could find to cleanly update the macro selection across pages.

Add AgentMacro

---

FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ModelResourceHandle.cs

Can the helper overloads be auto-generated or made shorter in any way? IIUC `[GenerateCStrOverloads]` only works for input `byte*` parameters, not output `byte*` + size couples or return values?

Add path resolution related methods

---

FFXIVClientStructs/FFXIV/Common/Math/Bounds.cs
FFXIVClientStructs/FFXIV/Common/Math/Vector2.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentDropDownList.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEvent.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkSimpleTween.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUldManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

Notes on AtkSimpleTween:
- AtkSimpleTween can be used on any AtkResNode, not just the RootNode of an AtkUnitBase.
- Can be used to tween values of X, Y, ScaleX, ScaleY, Alpha, Width, Height, or NodeText (on AtkTextNodes only).
- It's fine to call `Clear()` whenever - the animation will simply stop at the current values.
- It's not necessary to unregister events because they will be removed with the next `Prepare` call anyway.
- Any registered event that’s not of type TweenProgress or TweenComplete will be ignored.
- Special case: When the alpha value reaches 0, the node is automatically made invisible (the same as calling `AtkResNode.ToggleVisibility(false)`). To make the transition from 0 work you have to call `AtkResNode.ToggleVisibility(true)` first.
Example to toggle the Alpha value …

Update AtkUnitBase, Add AtkSimpleTween

---

FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs

Looks like this got missed in the 6.5 updates.
Not sure about the other 2 flag fields, the size of the struct didn't change though.

Fix weapon state offset

---

FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterSetup.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
ida/data.yml

Just adding a few random things around.
Added a few methods related to ActionTimeline stuff.
Looks like GetHeightAdjustActionTimelineRowId ended up in the wrong ActionTimelineManager in data, so that's fixed too.
I also documented a couple of CopyCharacter flags.
The ReadyToDraw flag is checked when calling EnableDraw and it will early exit if the flag is not set.
It's flagged true during an early frame at the top of Update on the GameObject typically.
Could be argued that it should be called HasHadFirstUpdate or IsReady similar so if you have a preference for a different name, let me know.
ObjectTargetableFlags may need renaming as it appears it contains more state that just whether something can be targeted, but I've left it as is for now (and I'm to blame for the name anyway).
I also …

Adding several things

---

FFXIVClientStructs/FFXIV/Client/Game/Control/Control.cs

A boolean that controls whether the local player should walk or not.
It's toggled at "88 83 ?? ?? ?? ?? 0F B6 05".
Technically it's at +0x55B inside some `Client::Game::Control::MoveControl` (located at Control + 0x5520), but this was a speedy commit to beat Kaz, so I didn’t look into it much further. ![WICKED](https://cdn.frankerfacez.com/emoticon/457124/1)

Add Control.IsWalking

---

FFXIVClientStructs/FFXIV/Client/Game/CurrencyManager.cs
ida/data.yml

This adds a CurrencyManager, used to track currencies.
These comments got a bit long. Any other idea on how to document this? Or not at all?
---
Example code:
```cs
string GetItemName(uint itemId)
=> Service.DataManager.GetExcelSheet<Item>()?.GetRow(itemId)?.Name.ToDalamudString().ToString() ?? "";
ImGui.TextUnformatted(nameof(CurrencyManager.SpecialItemBucket));
using (var table = ImRaii.Table(nameof(CurrencyManager.SpecialItemBucket) + "Table", 5))
{
if (table)
{
ImGui.TableSetupColumn("ItemId", ImGuiTableColumnFlags.WidthFixed, 100);
ImGui.TableSetupColumn("SpecialId", ImGuiTableColumnFlags.WidthFixed, 100);
ImGui.TableSetupColumn("Count", ImGuiTableColumnFlags.WidthFixed, 100);
ImGui.TableSetupColumn("Remaining", ImGuiTableColumnFlags.WidthFixed, 100);
ImGui.TableSetupColumn("Name", …
```

Add CurrencyManager

---

ida/data.yml

Uh, so yeah... InstanceContent event handlers.
I took some time to go through them, not sure if you guys want to add them. 🤷‍♂️
Couple notes:
- I took the names from classinformer.csv and tried to match them.
- Trials use `InstanceContentBattle` prefix based on classinformer.csv entries.
- I only inherited from InstanceContentDirector (and subtypes) for now. There is also a ContentSheetWaiterInterface and something else, but no clue about that.
- All dungeons/raids that I could queue for solo, I queued for and checked the vtable of whatever `EventFramework.Instance()->GetInstanceContentDirector()` returned.
- All Endwalker Dungeons use `InstanceContentDirector`, which is why there is no commit for them.
- I didn't process any Endwalker Trials or Raids due to queue times, except for the …

Add InstanceContent vtbls

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
FFXIVClientStructs/FFXIV/Client/Game/Control/GazeController.cs
ida/data.yml

It looks like the struct at Character+0xCB0 is used to handle head/eye-tracking, so I called it `GazeContainer`, if that's alright.
I use `BannerHeadDirection` and `BannerEyesDirection` already and wanted to add them, but then I went exploring.
Sadly I couldn't make much sense of it, but at least I learned about the `/facecamera` command which has fields in there (local player only?!). 👀
---
Other small changes on `Character`:
- Copied the field `Character.Movement` (fixed bytes) to `Character.MovementBytes` and marked `Character.Movement` obsolete, so it can be used for a struct in the future. I can also just mark it obsolete and don't make a new field, if thats better.
- Copied `LookTargetId` into `GazeController.TargetInfo` and marked the old one obsolete.
- Changed FieldOffset of …

Add Character.GazeContainer

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Component/SteamApi/Callbacks/AuthSessionTicketResponseCallback.cs
FFXIVClientStructs/FFXIV/Component/SteamApi/Callbacks/FloatingGamepadTextInputDismissedCallback.cs
FFXIVClientStructs/FFXIV/Component/SteamApi/Callbacks/GamepadTextInputDismissedCallback.cs
FFXIVClientStructs/FFXIV/Component/SteamApi/SteamApi.cs
FFXIVClientStructs/FFXIV/Component/SteamApi/SteamCallbackBase.cs
FFXIVClientStructs/FFXIV/Component/SteamApi/SteamTypes.cs
ida/data.yml

Creates a new `Component::SteamApi`, as I'm not really sure where else this stuff belongs.
The SteamAPI code appears to have been at least partially generated via templates/macros, and as such things may not be reflected properly.

First pass of SteamAPI

---

FFXIVClientStructs/FFXIV/Client/UI/AddonAOZNotebook.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonRecipeNote.cs
ida/CExporter/Extensions.cs

C#'s `char` type is UTF-16, so it's size is 2 bytes.
This PR changes CExporter to export C#'s `char` as `wchar_t`.
Since there are no `char**` fields I didn't add a case for it. 🤷‍♂️
I added some TODO comments to change `char*` to `byte*`, as I can't imagine that they are UTF-16.

CExporter: export char as wchar_t

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/BannerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

- Adds `UnlockedTripleTriadCardsBitmask` and `UnlockedTripleTriadCardsCount` to UIState
- Adds `HwdGathererInspection` to AgentId enum
- Adds `Equals` method to BannerModuleEntry
- Adds internal `GetRaptureAtkModule2` for the vtable in the exported structs
- data.yml updates:
- Adds `Client::Game::BGMSystem`
- Adds `ReadPacket` methods for UIState-related structs
- Adds `Client::Game::HWDManager` (name based on MJIManager), which seems to deal with the Diadem
- Adds `Client::UI::Agent::AgentHwdGathererInspection`
- Updated `Client::UI::AddonJobHud::AddonJobHudGaugeData` vtable address

Update UIState, BannerModule, data.yml

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
ida/data.yml

- Updates the `InventoryType` enum
- Taken from an internal array at 0x141A1E0B0.
- Type 2006 and 2008 are still unknown. I assume one of them is for trading with other players, and the other for getting items repaired by other players.
- There is also an id 9999, which i haven't added. It's a special id to indicate an invalid or unset container id. Not sure on the naming of that one.
- In addition, there are ids 2000 and 2013 that I have not added. I think these are start and end markers for the types in the 2000 range.
- Updates `InventoryItem` to support links.
- Allows InventoryItem to reference a specific, other InventoryItem based on the container type and slot id.
- In the case of a symbolic InventoryItem, the ItemId field is unused. Instead, it is divided into two ushorts: one for …

Update InventoryType and InventoryItem

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/GoldSaucerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This module stores Gold Saucer data (triple triad decks, unseen cards and the minion hotbar for Lord of Verminion) in `GS.DAT`.

Add GoldSaucerModule

---

FFXIVClientStructs.InteropSourceGenerators/FixedStringGenerator.cs

Just some small changes:
- Escaped the null terminator for the generated code
Before:
After:
- Renamed `p` to `ptr`
- Using hex format for max length
- Removed an unused `using` statement

Small FixedStringGenerator cleanup

---

FFXIVClientStructs.InteropSourceGenerators/FixedStringGenerator.cs

I forgot to add the `0x` prefix. Sorry.

FixedStringGenerator cleanup hotfix

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/PvpSetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This module stores - or rather stored - the selected additional PvP actions in a `PVPSET.DAT`.
Additional PvP actions have long since been removed from the game, so this struct layout is purely speculative and based on the ctor and ids I found in memory.
The index in the `AdditionalActions` array could've been the `JobIndex` column of the `ClassJob` row.

Add PvpSetModule

---

FFXIVClientStructs.InteropSourceGenerators/FixedStringGenerator.cs

This PR will add a setter to the FixedStringsGenerator.
- Checks `value` for `null` and uses `string.Empty` instead,
- Cuts the string off at max length, if it's longer,
- Always sets the null terminator at the end.
Seems to work. 🧐

Add setter to FixedStrings

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureTextModule.cs
ida/data.yml

I figured most people struggle with getting properly formatted names, especially for languages other than english.
This global, static function seems to be a helper to get the correct parameters for FormatAddonText to format a variety of names (Items, BNpcNames, ActionNames etc.).
Unfortunately, there is no support for plural forms, since adjusting `intParam2` (passed to FormatAddonText) doesn't seem to change anything.
I added helper functions with combinations that worked in my testing.
Like I said, it's a global function, and locaded very early on in the exe. It's probably not part of RaptureTextModule, but I didn't know where else to put it and since it uses RaptureTextModule, I thought it might fit there.

Add RaptureTextModule.FormatName and helpers

---

FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/MaterialResourceHandle.cs

This adds pretty much all of `MaterialResourceHandle`'s own fields, with span/string helpers.
Also, functions to construct color tables, that were already in the data file. (though, in the data file, it's still using the inaccurate wording "color set" where "color table" is meant)

Add MaterialResourceHandle fields and helpers

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkValue.cs

Found this type `0xB` in the `Component::GUI::AtkUnitBase_FireCallback(int valueCount, AtkValue* values, a4)` function.
It wraps the passed valueCount and values parameters in new AtkValues, and uses type `0x3` (Int) for valueCount and `0xB` for the `AtkValue*`.

Add ValueType: AtkValues

---

ida/data.yml

Not sure if @wolfcomp is available right now, so I just hacked this PR together.
Would be nice to get these PublicContentDirectors in before the data.yml update.
Same as https://github.com/aers/FFXIVClientStructs/issues/751 without the std::vector changes
(`Client::System::Threading::ThreadManager` has a dtor as vf0, which is why we're removing it from funcs)

PR #751 without std::vector changes

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
ida/data.yml

This function replaces text with other text.
It is used to replace attributive placeholders (`[p]`, `[a]`, `[pa]`, `[n]` and `[t]`).
Presumably for plain text only.

Add Utf8String.Replace

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
ida/data.yml

```cs
var test = Utf8String.FromString("Hello, this is a Test.");
var needle = Utf8String.FromString("Hello");
ImGui.TextUnformatted($"{test->ToString()}");
ImGui.TextUnformatted($"{needle->ToString()} {Utf8StringIndexOf(test, needle)}");
ImGui.TextUnformatted($"{needle->ToString()} {Utf8StringIndexOf(test, needle, 1)}");
needle->SetString("test");
ImGui.TextUnformatted($"{needle->ToString()} {Utf8StringIndexOf(test, needle)}");
needle->SetString("Test");
ImGui.TextUnformatted($"{needle->ToString()} {Utf8StringIndexOf(test, needle)}");
test->Dtor(true);
needle->Dtor(true);
```

Add Utf8String.IndexOf

---

ida/CExporter/Exporter.cs

This little change makes it so that CExporter can export non-public fields.

CExporter: export internal fields

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
ida/data.yml

I'm a bit ahead of time here. 😏
---
`AddonCabinetWithdraw` incorrectly had the vtable address of `AddonMoogleCollectionRewardList`.

Add MoogleCollection agent and addon

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
ida/data.yml

Couldn't find out what a4 does. 🤷‍♂️
Also, `everyWord` is only handled when `firstCharOnly` is true, otherwise the whole text is uppercase anyway.

Add Utf8String.ToUpper

---

FFXIVClientStructs/FFXIV/Client/Game/GameMain.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs

The lua function `IsOpenedFestival` (1408ED2E0) reads active festival ids from PlayerState. I assume the phases come right after, but can't tell for sure just yet. ~~Moogle Treasure Trove: The Second Hunt for Genisis should theoretically use the second phase of the same event. I'll leave this draft here until I can confirm it.~~
That said, `GameMain.ActiveFestivals` is not a `uint` array. Each festival entry has a ushort Id and a ushort Phase. Multiple xrefs confirm this, including the lua function `GetFestivalPhase` (1407D9ED0).   Sadly I can't add the FixedSizeArrayAttribute, because that only works on fixed byte arrays. I assume `GameMain.QueuedFestivals` has the same structure.

Add PlayerState.ActiveFestivalIds/ActiveFestivalPhases

---

FFXIVClientStructs/FFXIV/Client/Graphics/Physics/BoneSimulator.cs

Discovered this when messing around with the bone simulator and think it's worth adding.
This is a weird field, but messing around with it and reading the disassembly it seems to be a "springiness" value. It starts a little lower than 60.0, but anything higher than that results in relentless jitter. Lower values such as 0.0 completely remove the springiness/bounce.

BoneSimulator: Add Spring field

---

FFXIVClientStructs/FFXIV/Client/Sound/SoundManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/EnvironmentManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Client/System/Input/Cursor.cs
ida/data.yml

As to prior questions: The volume setters in EnvironmentManager are to my understanding the intended API to use for volume changes (permanent and temporary) 
Has been discussed in the [discord](https://discord.com/channels/581875019861328007/653504487352303619/1201162708528152666) ~~@KazWolfe Maybe you can propose a wrapper function that makes this most easy to use~~ 
Note: I included some generic functions/fields that I found on the way, and I deemed safe to include

Environment Manager + Cursor 

---

FFXIVClientStructs/STD/Tm.cs

Seems like I f*d it up. Is this correct now?
**tm_mday**: day of the month – [1, 31]
**[DateTime.Day](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.day?view=net-8.0)**: The day component, expressed as a value between 1 and 31.
**tm_wday**: days since Sunday – [​0​, 6]
**[DateTime.DayOfWeek](https://learn.microsoft.com/en-us/dotnet/api/system.dayofweek?view=net-8.0)**: Sunday 0 - Saturday 6
https://en.cppreference.com/w/cpp/chrono/c/tm

Fix tm days being off by 1

---

.github/workflows/cexporter.yaml
.github/workflows/pr-breaking-change-check.yaml

Updated CExporter action to comment with what is wrong and add the requested changes label.
Added ABI check between target and source branches of pr and automatically assign tag if breakage happens.
These currently won't work due to some weirdness about how permissions are handled, and it's only getting read instead of write access.
Both actions only add but never remove the tags that have been added if a workflow finds something that needs to be changed or there is an ABI break, but then it's fixed later.

Update GHA to automate a bit more of checks

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/RenderTargetManager.cs

`1403D1790`, there's a few more but I wasn't confident on what they do. Set `rtm->DynamicResolutionTargetHeight = 1; rtm->DynamicResolutionMinimumHeight = 1;` in framework update for a fun time.

Add some fields for dynamic resolution

---

FFXIVClientStructs/FFXIV/Client/Game/CSBonusManager.cs
ida/data.yml

Used for the Mogpendium.
Names come from the `PrintDebugInfo` function.

Add CSBonusManager

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkUnitManager.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs

- Updated and added back in some older offsets
- Obsoleted `PartyEnmityList` in favour of new FixedSizeArray fields
- Added `MiniMapGatheringMarkers` containing markers for 
- mineral deposit and lush vegetation patch,
- legendary mineral deposit,
- unspoiled lush vegetation patch,
- possibly more in the other 3 entries, but I have not been able to figure out what they are used for.
- Added `MapMarkers` containing map markers for directors, quests, housing, and more?! I'm not quite sure what it all contains.

Some AgentHUD additions

---

ida/data.yml

The third parameter of `FormatAddonTextApply` is the reason for the function names `FormatAddonText1`/`FormatAddonText2`.
If anyone finds out what the parameter does, we can maybe properly name those functions.

Add FormatAddonText overloads

---

FFXIVClientStructs/FFXIV/Component/Text/ReferencedUtf8String.cs
FFXIVClientStructs/FFXIV/Component/Text/TextParameter.cs
ida/data.yml

`TextParameter` doesn't hold a plain `Utf8String`, but a struct containing the `Utf8String` and a `RefCount`.
I called it `ReferencedUtf8String `, based on [ReferencedClassBase.cs](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/Graphics/ReferencedClassBase.cs).
The game calls the Utf8String.dtor and frees the `ReferencedUtf8String` if RefCount is 0 when setting a new value or cleaning up.
I didn't know where to put it, so I placed it in the same namespace as `TextParameter`.

Add ReferencedUtf8String for TextParameter

---

ida/data.yml

This PR adds 238 out of 239 `Client::Game::Event::EventSceneModuleImplBase` vfuncs to the data.yml.
These are all called by lua functions, which is where their names come from.
The only one missing a name is vf214, because it is called from a sub-function of `ActionManager_GetActionStatus` (at `E8 ?? ?? ?? ?? 84 C0 0F 84 ?? ?? ?? ?? 48 8B B4 24`).

Add EventSceneModuleImplBase vfuncs

---

FFXIVClientStructs/FFXIV/Client/Game/Control/Control.cs
ida/data.yml

It kinda bugs me that we only have access to the local player character via a `LocalPlayer` field in `Control` or via index 0 of the ObjectList/BattleCharaList, which is why I added a more direct StaticAddress function to access `g_LocalPlayer` with `CharacterManager.GetLocalPlayer()`.
The sig is exactly where it sets the `g_LocalPlayer` variable in `CharacterManager`, so I thought this is fitting in there.

Add Control.GetLocalPlayer

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Buddy.cs

Not sure why these are private. Must have happened by accident. 🤷‍♂️

Make fields public in CompanionInfo

---

FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBRD.cs

Fixed a couple of wrong offsets in the BRD gauge.
There seem to be a few more fields within the struct that aren't yet documented, but I'm not too fussed about those; 7.0 is going to break various job gauges in a couple months (and there's no way to know which ones), so outright error-fixes are the only updates I'd bother making.

Offset corrections for BRD gauge

---

ida/data.yml

This PR adds agent getter functions to the data.yml.
The following ones do not have any callers, so I left them out (unless I should add them? seems pointless 🤔 ):
```
0x140225660: GetAgentScenarioTree
0x140225670: GetAgentMateriaAttach
0x140225710: GetAgentTourismMenu
0x1402257F0: GetAgentPerformanceMode
0x1402258F0: GetAgentTofuList
0x140225940: GetAgent142
0x140225950: GetAgent433
0x140225980: GetAgentContext
```

Add Agent getters to data.yml

---

FFXIVClientStructs.InteropSourceGenerators/AgentGettersGenerator.cs
FFXIVClientStructs.InteropSourceGenerators/InfoProxyInstanceGenerator.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoModule.cs

~~Stacked PR~~, based on https://github.com/aers/FFXIVClientStructs/pull/855 to make it an optional change.
This PR marks `GetAgentByInternalID(uint)` and `GetInfoProxyById(uint)` obsolete and makes the enum variants the primary and only getters. Users can just cast to AgentId/InfoProxyId if an something is missing in the enum. 🤷‍♂️

Obsolete uint Agent/InfoProxy getters

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentDetail.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCommonList.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxySearchComment.cs
ida/data.yml

This should roughly be the code that's needed to open the Search Info window for the local player:
```cs
var infoModule = InfoModule.Instance();
if (infoModule->IsInCrossWorldDuty())
return;
var localContentId = infoModule->GetLocalContentId();
var characterData = InfoProxyParty.Instance()->InfoProxyCommonList.GetEntryByContentId(localContentId);
if (characterData == null)
return;
var updateDataPacket = &InfoProxySearchComment.Instance()->UpdateData;
AgentDetail.Instance()->OpenForCharacterData(characterData, updateDataPacket);
```
---
I also updated `InfoProxySearchComment`, so it's possible to send online status and search comment updates.

Add AgentDetail and update InfoProxySearchComment

---

FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxySearchComment.cs

I forgot a parameter..
I know it's breaking change, but it didn't land on Dalamud stable yet and Una is the only one currently testing it.
```c
void __fastcall Client::UI::Info::InfoProxySearchComment_SetUpdateOnlineStatus(
Client::UI::Info::InfoProxySearchComment *a1,
Client::UI::Info::InfoProxyCommonList::CharacterData::OnlineStatus a2,
bool skipAwayFix)
{
a2a = a2;
if ( a1->UpdateData.OnlineStatusMask != a2 )
{
if ( !skipAwayFix && (a2 & 0x20000) != 0 )
{
Client::UI::Info::InfoProxySearchComment_FixOnlineStatusFlag1(a1, &a2a);
Client::UI::Info::InfoProxySearchComment_FixOnlineStatusFlag2(a1, &a2a);
a2 = a2a;
}
a1->UpdateData.OnlineStatusMask = a2;
a1->HasUpdateData = 1;
}
}
```
`log2(0x20000) = 17`, the Away status. I think it removes the Mentor/Novice/RP/Returner/Trial statuses …

Fix SetUpdateOnlineStatus params

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs

A scale value of 132 doesn't make sense, but a radius of 123 does.
Also TempMapMarker was 8bytes too small.
I verified that these fixes are correct by implementing them into Mappy.

AgentMap small fixes

---

FFXIVClientStructs/FFXIV/Client/Game/Event/Director.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/ContentDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/DirectorInfo.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/DirectorTodo.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

`DirectorTodo` is a small struct in UIState that acts as a proxy to get data from a Director for the number/string arrays that the Todo addon uses. It is used for both, ActiveDirector and FateDirector. Sadly, I can't make generic structs with an explicit layout, so everyone who currently uses FateDirector will have to cast the Director to `FateDirector*`.

Add DirectorTodo, update Director and EventHandler

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandler.cs

Kaz asked to prefix the parameters with out (https://github.com/goatcorp/Dalamud/pull/1805#pullrequestreview-2065123720).
I totally forgot this is a thing we do already, so here is the change.

Prefix params with out

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentChatLog.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemComp.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemCompare.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxy20.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyNoviceNetwork.cs
ida/data.yml

- Rename InfoProxy20 to InfoProxyNoviceNetwork
- Add LinkItem to AgentChatLog
- Add AgentItemComp
For `InviteToNoviceNetwork(ulong contentId, ushort worldId, byte* name);` i assume it is contentId, but chat2 just pushes 0 in all cases
Sigs taken from <https://github.com/Infiziert90/ChatTwo/blob/main/ChatTwo/GameFunctions/Context.cs>

Changes InfoProxy20, AgentChatLog and adds AgentItemComp

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObjectManager.cs

Changes the arrays to be correctly typed.
This is verified with both looking at some of the index lookups in source and ReClass

Fix GameObjectManager

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/FieldMarkerModule.cs

Remove field that was only used for padding when struct was defined as sequential.
Field doesn't even need to be private, it's just padding.

FieldMarkerModule

---

FFXIVClientStructs/FFXIVClientStructs.csproj
InteropGenerator.Runtime/InteropGenerator.Runtime.csproj

This PR enables
- [ContinuousIntegrationBuild](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#continuousintegrationbuild) to normalize file paths in pdb files, and
- [Deterministic](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#deterministic) to produce byte-for-byte identical dlls across compilations for identical inputs.

Enable deterministic CI builds

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkTextNode.cs

These are no longer necessary, as GenerateStringOverloads implements methods that can implicitly cast these args

AtkTextNode Remove Manual Overloads

---

FFXIVClientStructs/FFXIV/Component/GUI/ExtendArrayData.cs
FFXIVClientStructs/FFXIV/Component/GUI/NumberArrayData.cs
FFXIVClientStructs/FFXIV/Component/GUI/StringArrayData.cs

- finally getting rid of the overloads we added last year
- changing the parameter name `silent` to `suppressUpdates` to make clear what it does
- adding comments to `StringArrayData.SetValueForced`
- removing `GenerateStringOverloads` from `StringArrayData.SetValueForced`. it only stores pointers and does not make a managed copy of the text
- added default values to not so important parameters

Remove old ArrayData.SetValue overloads and update comments

---

FFXIVClientStructs/FFXIV/Client/System/Scheduler/ActionTimelineManager.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Resource/SchedulerResourceManagement.cs
ida/data.yml

I revisited this function because I encountered T-Poses. While doing so I found it was passing a small struct containing the Key **and** an Index of the loop in `sub_1404DBEB0`.
The index is probably used as some kind of cache id, since it offsets WeaponTimeline indexes by 0x20000 (it also sets it to `SchedulerResource.Unk1`, but I didn't look into it more).
Since it now takes a new struct `PreloadActionTmbInfo`, I renamed the function from `PreloadActionTmbByKey` to `PreloadActionTmb`.
I also removed `GetActionTimelineKey()` since it wasn't really part of the `ActionTimelineManager`, `GetWeaponTimelineKey()` is not siggable and you can just get the Key from the Lumina sheets.

Fix PreloadActionTmbByKey

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerEditor.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkUnitManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitManager.cs
ida/data.yml

- Moved functions from `RaptureAtkUnitManager` to `AtkUnitManager`
- Renamed vf8 from `ShowAddonByID` to `SetAddonVisibility`, because passing false as second parameter hides the addon (open for name suggestions - `UpdateAddonVisibility`? `ChangeAddonVisibility`?)
- Renamed `PlayerState.OwnedMountsBitmask` to `PlayerState.UnlockedMountsBitmask` to align it with the names of other unlock bitmask fields
- Changed the type of `AgentBannerEditorState.FrameCountdown` to float. I found this in a 7 month old git stash. 🙃 Confirmed float at 1412CDDEC.

Update AtkUnitManager and some small changes

---

FFXIVClientStructs/FFXIV/Client/Game/GcArmyManager.cs
FFXIVClientStructs/FFXIV/Client/Game/GoldSaucer/GFateDirector.cs
FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentBozja.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIGranariesState.cs
FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFreeCompanyProfile.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyLetter.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/BannerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/FieldMarkerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs
FFXIVClientStructs/FFXIV/Common/TimePoint.cs

Whether or not timestamps ever go back further than 01.01.1970, the fields should still be of type `int`.

Change timestamp types to int

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.HotBarSlot.cs

Per request from @MidoriKami, adds back `IconA`, `IconB`, `IconTypeA`, and `IconTypeB` with an obsolete pointing to the new field names.
I'm still honestly not sold on the names `ApparentActionId` and `OriginalApparentActionId`, but I also can't think of any better ones (`BaseApparentActionId` maybe?).
Obsoletes to be removed eventually after apiX release.

chore: Add IconA/IconB obsoletes pointing to new fields.

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitManager.cs

Addon Lifecycle originally tried to use OnRefresh as a `void` return, but that caused a bunch of corruption errors, we discovered this issue and fixed it using our own delegate. Since then ClientStructs has added these functions, but they were added with the wrong return type.
```cs
char Component::GUI::AtkUnitBase_OnRefresh()
{
return 1;
}
```
```cs
char __fastcall Component::GUI::AtkUnitManager_RefreshAddon(
__int64 a1,
Component::GUI::AtkUnitBase *a2,
unsigned int a3,
Component::GUI::AtkValue *a4)
{
if ( !a2 )
return 0;
Component::GUI::AtkUnitBase_SetAtkValues(a2, a3, a4);
return (a2->union.vtable->OnRefresh)(a2, a3, a2->AtkValues);
}
```

[Not Dawntrain] Fix incorrect return type

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/EnvironmentManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerEditor.cs
FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyNoviceNetwork.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs

I checked signatures that aren't resolving to a jmp or call and didn't end up at the start of a function. Only 5 results.
InventoryItem.EqualTo was a random find as I checked it after updating the Ctor. It was resolving to the start of a function but it was an entirely different one. A mistake in my big sig update list.

[Dawntrail] Update more signatures

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentTryon.cs

Note: The last parameter of the TryOn function was incorrect.
The InventoryItem flag CompanyCrestApplied is checked and passed to it in `E8 ?? ?? ?? ?? 40 88 6E 08 EB 5F` (EW) / `E8 ?? ?? ?? ?? EB 70 48 83 FB 03` (DT).
Also added default values to make it easier to use.

[Dawntrail] Update Client::UI::Agent::AgentTryon

---

FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutManager.cs
FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutWorld.cs
ida/data.yml

Adds a function to prefetch a layout and another one to cancel it.
`LayoutWorld.PrefetchLayout` is called with type 1 and [LayerEntryType](https://github.com/NotAdam/Lumina/blob/master/src/Lumina/Data/Parsing/Layer/LayerEnums.cs) 71 (PrefetchRange) when near a zone barrier, or with type 2 and LayerEntryType 40 (PopRange) when starting to cast Teleport.

Add layout prefetch functions to LayoutWorld

---

FFXIVClientStructs/FFXIVClientStructs.csproj

This is required for docs generation on our end. docfx can't work directly with source generators.
If it was disabled on purpose, maybe it could be enabled conditionally?

Emit generated source files

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismPrismBox.cs

At a guess this is the slot on the server, useful for those needing to keep track of a glamour chest item's real position

Add Slot to PrismBoxItem

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGaugeEnums.cs
FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

Updated PCT gauge with values at max level.
- White Paint => Paint (Black Paint is controlled by a buff and the gauge only shows it visually but isn't tracked by the gauge)
- Updated creature flags
- I suspect Maw would have a creature flag of 8, however given that using Maw instantly sets the Madeen portrait it currently isn't used and therefore cannot prove that.

PCT gauge update

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemDetail.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkTooltipManager.cs

Adds some missing fields to `AgentItemDetail` and `AtkTooltipManager` used by ChatTwo. All of these are used in the plugin except a new unknown `Utf8String` field which I added for posterity.
Thanks to @Infiziert90 for helping with these

Update AgentItemDetail and AtkTooltipManager

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs

Can someone confirm this is right?
Now hex-rays shows `*(_QWORD *)&this->Radius = LODWORD(radius);` 🤔

Fix radius type of MapMarkerData.SetData

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/Manager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/ModelRenderer.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/SubView.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/View.cs

I fixed an offset that was obviously wrong in SubView, but as I don't use this struct, I cannot know for sure whether it is now entirely correct.

Update RenderManager/ModelRenderer offsets and sizes for 7.0

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
ida/data.yml

`AtkUnitBase.GetComponentNodeById` currently returns an incorrectly cast `AtkComponentBase`
I've renamed the original to `GetComponentByNodeId` based on what it actually does, and added a temporary function to avoid breaking the API

fix AtkUnitBase.GetComponentByNodeId

---

FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsFinder.cs

Updates the data type of the following properties of the `ContentsFinderQueueInfo ` struct to be `uint` rather than `byte`:
- `QueuedContentFinderConditionId1`
- `QueuedContentFinderConditionId2`
- `QueuedContentFinderConditionId3`
- `QueuedContentFinderConditionId4`
- `QueuedContentFinderConditionId5`

Update the ContentsFinderQueueInfo ConditionId data types

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkClippingMaskNode.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
ida/data.yml

This is essentially an image node with a monochrome texture loaded, which serves as a mask for other nodes in the draw list.
Every example I've found of this type has been located within an `AtkComponentNode`, rather than being in the Addon's main node list. The mask is seemingly applied to the `NextSiblingNode` and to all subsequent siblings within the Component. It is not applied to previous sibling nodes, or to nodes outside the Component.

Add AtkClippingMaskNode

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHUD.cs
ida/data.yml

These fields are used as a cache for the UpdateExp function, so it updates the (Number|String)Arrays only when needed.

Update AgentHUD (_Exp fields)

---

FFXIVClientStructs/FFXIV/Client/UI/AddonPartyList.cs

This is the main AtkResNode containing all the other things, also used to identify the PartyList alignment for ReadyCheckHelper

Add missing AtkResNode in AddonPartyList

---

FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs

Not sure why there was no overlap error from the gh action. 🤔

Fix sizes of unlocked bitmasks in UIState

---

FFXIVClientStructs/FFXIV/Client/UI/AddonJobHudBLM.cs
ida/data.yml

- Corrected inheritance in `data.yml`; Simple gauges are now correctly documented as inheriting from their standard versions.
- Fixed incorrect offsets within BLM1 Gauge
- Added missing addresses for RPM0 Gauge

AddonJobHud Fixes

---

FFXIVClientStructs.StdContainerTester/StringTester.cs
FFXIVClientStructs/STD/Helper/IStaticEncoding.cs

Since `CodePagesEncodingProvider.Instance.GetEncoding(0)` fails for some people, implemented a custom version using Windows APIs.

Implement alternative IStaticEncoding provider

---

FFXIVClientStructs/FFXIV/Client/UI/AddonNeedGreed.cs

Fix size of LootItemInfo struct, it got 2 bytes bigger in 7.0

AddonNeedGreed

---

FFXIVClientStructs/FFXIV/Client/UI/AddonGathering.cs

- Adds a FixedSizeArray `GatheredItemComponentCheckbox`
- Obsoletes `GatheredItemComponentCheckbox#` in favor of the above

Add FixedSizeArray in AddonGathering

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventSceneModuleTaskManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventSceneTaskInterface.cs
ida/data.yml

I originally named it `HairMakeTask` because of the lua function HairMake which sets it up.
Found the name `CharaMakeInGameTask` in the old exe.

Rename HairMakeTask to CharaMakeInGameTask

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs

Adjusted with @wolfcomp's help
`AgentContentsFinderUnkItemsSub` seems to be yet another copy of all the items

Agent content finder

---

FFXIVClientStructs/FFXIV/Client/UI/AddonAreaMap.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonNamePlate.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGrandCompanySupply.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkArrayData.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs

This PR is a continuation of and supersedes #1073.
- Moved `NumberArrayType` and `StringArrayType` from underneath `AtkStage` to underneath the `AtkArrayData` struct and updated them with many new types.
- Added `ExtendArrayType`.
- Added `AtkStage.GetExtendArrayData(ExtendArrayType)`
- Renamed `AddonAreaMap.AreaMapIntArrayData` to just `AddonAreaMapNumberArray`.
- Marked `AddonNamePlate.NamePlateIntArrayData` obsolete (because it already existed before the other PR), and moved/renamed it to just `AddonNamePlateNumberArray`.
Closes #1073

Add AtkArrayData types

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
ida/data.yml

I'm not quite sure what's going on.
- The function `IsAdventureComplete` didn't return what we expected.
- I found out that `IsAdventureExPhaseComplete` actually returns whether a vista was discovered, so I moved the sig over to `IsAdventureComplete`.
- Tried to figure out where `IsAdventureExPhaseComplete` is, but I can't find it. Maybe they reworked it? Didn't check old exes. Marked it obsolete and removed it from data.yml.
-  I added `SetAdventureUnlocked`/`IsAdventureUnlocked` functions to the data.yml and renamed `_unlockedAdventureExPhaseBitmask` to `_completedAdventureBitmask`, but I'm not sure if that's correct, because I already unlocked the sightseeing log for all expansions, which is why I didn't add the functions to PlayerState.cs.

Fix PlayerState.IsAdventureComplete

---

.github/workflows/pr-change-check.yaml

When pushing multiple commits in a row (separately, for example I just realized I need to rebase after I pushed), several jobs of the `pr-change-check` action run in parallel.
In the worst case scenario where one action could be a bit slower with building than the other, it can cause the comment from a newer commit to be deleted and replaced with an older one.
This change adds concurrency to the action, cancelling running `pr-change-check` jobs on the same PR, so that only the last started action is allowed to comment.
I used the example from the [GitHub docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-using-concurrency-and-the-default-behavior). The `github.workflow` context contains the name …

ci: Add concurrency to pr-change-check

---

.github/workflows/pr-change-check.yaml

Reverts aers/FFXIVClientStructs#1097 due to breaking ci currently

Revert "ci: Add concurrency to pr-change-check"

---

FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
FFXIVClientStructs/FFXIV/Component/Shell/ShellCommands.cs

- New `ShowCommandErrors` field controls whether errors are printed to chat or not.
- `ErrorData` is... weird and seems to be combined flags with a byte.
- Read in `RaptureShellModule.vf1` as a byte
- Set in many commands as a full dword with value 0x50007 or 0x5000E
- Give up and finally add `ProcessChatBoxEntry` to UIModule.
- The functionality this command exposes is already done via `ExecuteCommandInner` so I think it's a bit late to play the safety game.
- I'd even argue this variant is safer since it *does* properly manage RaptureShellModule's state.

Add some more command things

---

FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkExternalInterface.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModuleEvent.cs
ida/data.yml

*Can* be used to make a function that calls a handler to send a chat message instead of adding a lose method ProcessChatBoxEntry in kaz's PR.
0x141175F9C is where the game calls the AtkModule handler, which calls the UIModule handler.

Add UIModuleHandler

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs

Must have changed in one of the recent patches
for exmaple `1407b8ac0` writes to these higher offsets now

[RaptureLogModule] Update to new size and include new fields

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLookingForGroup.cs

Most of the `Detailed` struct fits the packet PartyFinderListing, so i sticked with names used in that packet

Add content to AgentLookingForGroup

---

FFXIVClientStructs/FFXIV/Client/Game/GameMain.cs
ida/data.yml

While `GameMain.IsInSanctuary` is missing a parameter, the function is intended to check if Glamour Plates can be applied in the current territory. It contains a check whether the player has the general action "Cast Glamour" unlocked and is soley used in glamour-related code.
The games experience bar uses `TerritoryInfo.Instance()->InSanctuary` at the end of `AgentHUD.UpdateExp`, so I think we should use that too.
<details>
<summary>Decomp of GameMain.IsInSanctuary</summary>
```c
bool __fastcall Client::Game::GameMain_IsInSanctuary(bool checkCastGlamourUnlocked)
{
Client::UI::UIModule *UIModule; // rax
Client::UI::Info::InfoModule *v2; // rbx
Client::Network::NetworkModuleProxy *NetworkModuleProxy; // rax
char v4; // al
bool result; // al
result = 0;
if ( !checkCastGlamourUnlocked
|| …
```

Obsolete GameMain.IsInSanctuary

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventFramework.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

added `GetPosition` method on GameObject, the address was already in data.yml
added `CheckInteractRange` on EventFramework, which calls GetPosition internally
the result of GetPosition is used for checking interact range as well as attack range. a value different from the Position field on the struct can be returned from the object's LayoutInstance or the DrawObject.

methods for getting correct interact range on objects

---

FFXIVClientStructs/FFXIV/Application/Network/LogoutCallbackInterface.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/ShopEventHandler.cs
FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutWorld.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkMessageBoxManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModule.cs
ida/data.yml

- When Logout or Exit Game is clicked in the system menu, both end up in `AgentLobby.HandleLogout` (after the countdown is over, if there is one).
- When the server closes the connection, or the game loses connection, `LogoutCallbackInterface.OnLogout` is fired with the error code.

Add LogoutCallbackInterface

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/PronounModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModuleInterface.cs
FFXIVClientStructs/FFXIV/Common/Component/Excel/ExcelModule.cs
FFXIVClientStructs/FFXIV/Common/Component/Excel/ExcelModuleInterface.cs
FFXIVClientStructs/FFXIV/Component/Excel/ExcelModuleInterface.cs
FFXIVClientStructs/FFXIV/Component/Text/Localize.cs

The internal field ExcelModule in UIModule was incorrect.
ExcelModule inherits from `Common::Component::Excel::ExcelModuleInterface`, but the field is storing a pointer to `Component::Excel::ExcelModuleInterface` (without the Common:: prefix). It's a different thing.
Changes:
- UIModule vf2 was renamed from `GetExcelModule` to `GetExcelModuleInterface`, though that is still confusing since there are 2 of those.
- The other ExcelModuleInterface (with Common prefix) was added as struct and ExcelModule now inherits from it.
- GetLanguage() vfuncs were added to both interfaces with their respective enums. (I'm not sure if the ExcelLanguage enum with the None value should be living somewhere else, like in ExdModule or ExcelSheet.)
The values for the ExcelLanguage enum were taken from Lumina: …

Correction of ExcelModuleInterface

---

FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Device.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Texture.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/GraphicsConfig.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/OffscreenRenderingManager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/RenderTargetManager.cs
ida/data.yml

Preface: It's a bunch of nothing.
Wanted to check in on CharaView rendering again, but ended up just updating RenderTargetManager, which wasn't updated for Dawntrail. I tried to map fields, but sadly I lack the knowledge of graphics engine internals, which is why I couldn't name anything and simply set all unk fields to internal so they can at least be used with the structimporter. (Stupidly enough the generated FixedSizeArray Spans are public... not my fault.)
I couldn't find the DynamicResolution height fields - they probably were replaced by aspect ratio floats.
Also, I added the GraphicsConfig struct. Most fields are updated from ConfigOptions, which is where I got the names from (see `48 89 5C 24 ?? 48 89 74 24 ?? 57 48 81 EC 90 04 00 00`).

Update RenderTargetManager, add GraphicsConfig

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkValue.cs

The type 0xC is used in `Component::GUI::AtkModule_PlaySoundEffectHandler`, which makes them a general pointer type now.

Rename AtkValue type Texture to Pointer

---

FFXIVClientStructs/FFXIV/Client/Game/GameMain.cs
FFXIVClientStructs/FFXIV/Client/UI/UIGlobals.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
ida/data.yml

This PR adds the `UIGlobals` struct, which serves as a central place for storing global static functions from the `Client::UI` namespace.
Some of these global functions were added to other structs in the past, which is why they have been moved to UIGlobals:
- `GameMain.IsInSanctuary`, moved as `CanApplyGlamourPlates` (see also: #1123)
- `UIModule.PlaySound`, moved as `PlaySoundEffect`
- `UIModule.IsPlayerCharacterName`, moved as `IsValidPlayerCharacterName`
- `UIModule.PlayChatSoundEffect`
The entries in the data.yml have also been renamed accordingly, though I did not add the namespace prefix if it was missing.
I've also added the `IsExportedGatheringPointTimed` function (formerly named IsGatheringTypeRare by me in the data.yml) to this struct (because I need it myself), and tried to add …

Add UIGlobals struct

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs

This was changed some time ago in the game. Easiest way to see how this new argument is used is looking at Character.GetRadius override.

Fix GameObject.GetRadius signature.

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs

Seems to be a copy paste mistake from copying EqualTo.

Fix return type of InventoryItem.Copy

---

FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs

Used by GameGui in Dalamud.
Can replace https://github.com/goatcorp/Dalamud/blob/fea5b3b563ba9b42b6d03881ac27d6c95ef75800/Dalamud/Game/Gui/GameGui.cs#L139-L166
with 
```cs
public unsafe bool OpenMapWithMapLink(MapLinkPayload mapLink)
{
return RaptureAtkModule.Instance()->OpenMapWithMapLink(mapLink.DataString);
}
```

Add RaptureAtkModule.OpenMapWithMapLink

---

ida/data.yml

To fix some ffxiv_idarename.py problems:
- Removed ShopEventHandler 2nd and 3rd inheritance.
- ToolBank had the wrong address.
- Moved FilterSead above LowpassFilterSead, because they share functions that aren't in the FilterBase.
- Memset is named by IDA already.

data.yml fixes

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkEvent.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEventDispatcher.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEventManager.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkSimpleTween.cs
ida/data.yml

Lost track multiple times, so I'm not sure about the AtkEventStateFlags anymore.
By the way, it's correct, that ReceiveEvent is passed a word. The game uses the first 2 bytes of AtkEventState and masks it with 0xFF before passing it. Since it doesn't change anything for us, it can stay AtkEventType.

AtkEvent system changes

---

FFXIVClientStructs/FFXIV/Client/UI/LogViewer.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEventData.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkTextNode.cs
ida/data.yml

Unsure how this all fits together. There is a lot of font stuff involved (to calculate text positions?).
Also, I didn't know how to properly map PayloadEndAndLinkType, so I added CExportIgnoreAttribute to it.
- At `41 8B 4C 24 ?? 41 8B 5C 24` it uses a bitshift to get the payload length:
`v5 = (int)(*(_DWORD *)&v2->PayloadEndAndLinkMacroPayloadType << 8) >> 8;`
- At other places (e.g. `41 0F BE 7D ?? 83 FF 03`) it gets the `LinkType` directly.
Also, UIntValue1 to 3 are the link parameters, but maybe they should be Int?

Add LinkData (for AtkTextNode/AtkEventData)

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentList.cs

`AgentLobby` got shifted by `0x68` somewhere after `LobbySheet` and a further `0x8` somewhere after `HoveredCharacterContentId`
`AtkComponentList` also had some stuff shifted after `ItemRendererList`
Things might have been rearranged too didn't dive too deep to figure stuff out.

Partial AgentLobby and AtkComponentList offset fixes

---

FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs

Function is not static and requires a `UIModule` pointer as the first parameter

Fix UIModule::ProcessChatBoxEntry

---

Ghidra/Getting Started.md

This is already in the IDA instructions, because the current version of anytree doesn't support Python 2.

Specify anytree 2.8.0 in the Ghidra instructions

---

FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs

Was previously `BattleChara.Flags2 & 0x80`, disappeared in one of the 7.1 changes.
From @awgil:
> interesting, it's set by actorcontrol 32
> it's now at offset 0x1C68, value is 0x40
Not really sure what the best name for it is, all things considered, as I'm not sure where else its used.
Tested while doing 'Combat Evolved' (Ultimate Thule aether current quest) on an alt.

Restore missing flags on Character

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs

`*(byte*) ((nint) (&chara->TargetableStatus) + 1) = 0;` works, but `chara->TargetableStatus = 0` does not, so I bumped the offset by 1.

Correct GameObject TargetableStatus offset

---

FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/ContentDirector.cs

This also got shifted by +0x50. This is required for the Distant Seas timer (see https://github.com/NotNite/DistantSeas/issues/12).

Fix offset in ContentDirector

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHousingInteriorPattern.cs
ida/data.yml

Nothing useful here... controls the addon(s) and sends commands to the server to get the list and confirm the choice, I think.
Excel notes: I think HousingRenovation.Unknown1 is a TerritoryType RowId. It's used as RowId of HousingIndoorTerritory.

Add AgentHousingInteriorPattern

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventFramework.cs

EventFramework->GetPublicContentDirector() was updated in 7.1, but with the signature of GetPublicContentDirectorByType(PublicContentDirectorType), so right now its being called with PublicContentDirectorType=0 returning always null

Fix signature of EventFramework->GetPublicContentDirector()

---

ida/ffxiv_structimporter.py

As per https://pyyaml.org/wiki/PyYAMLDocumentation, we can make use of LibYAML, which is a python parser written in c that is much faster than the default one written in python.
Worked out of the box for me and cut down ffxiv_structs.yml loading time from 29.4s to 2.8s.

structimporter: use LibYAML loader if available

---

FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs

Needed so that we can manually call `SetupSteamApi()` from Dalamud/plugins.
The game will automatically tear down the Steam API when shutting itself down, so long as the SteamApi pointer is set (see `Client::System::Framework::Framework_TeardownSteamApi`, inlined in `Framework#Free`.
This method must only be called once per session, so callers need to verify first that `IsSteamApiInitialized` returns `false`, and that `boot/steam_api64.dll` is present. If a Steam API is already present, re-calling this method will reinitialize the API, leading to potentially problematic edge cases.
Likewise, if this method is called when `boot/steam_api64.dll` is not present, it will set the variable `Framework#IsSteamGame` to `true`. However, this does not appear to actually do anything, so perhaps this …

Add SetupSteamApi to Framework

---

ida/luminapie/exdschema.py

Releases are in order, so we have to reverse the list to pick the previous one.

exdschema: fix version fallback

---

FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutWorld.cs

I didn't see this correctly, because it passes GameMain.Instance() to the function and the ActiveFestivals array is at offset 0 in GameMain.
It dereferences the pointer at 1406B9D8D and copying the festivals as _OWORD, so since GameMain.Festival is of size 0x4 it copies all 4 festivals.

Fix LoadPrefetchLayout festivals arg

---

FFXIVClientStructs/FFXIV/Client/System/Photo/ScreenShot.cs
ida/data.yml

As best seen in `Client::System::Photo::ScreenShot_Setup`

fix `ScreenShot` instance to be a pointer

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/WorldHelper.cs
ida/data.yml

Looks like the field was removed, so the name was cut off in the beginning.

Remove WorldHelper::World.IsPublic

---

FFXIVClientStructs/FFXIV/Client/LayoutEngine/LayoutWorld.cs
ida/data.yml

I thought adding this should make it easier to get a specific instance than going via the InstancesByType map.
Wasn't sure how to differenciate the static and the non-static by name, so I added the static one under global functions. Seems to fit based on nearby functions. 🤷‍♂️

Add LayoutWorld.GetLayoutInstance

---

FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureTextModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkInputManager.cs
ida/data.yml

Was dealing with EventFramework tasks and stumbled upon this. Thought it might be useful for someone.
Technically it just sets MacroCurrentLine to -1 and MacroLocked (and the byte after) to 0.

Add RaptureShellModule.CancelMacro

---

FFXIVClientStructs/FFXIV/Client/Game/Event/ShopEventHandler.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHousingPlant.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInventoryContext.cs
ida/data.yml

Just for inheritance. Didn't look into what it does.
But I noticed that the ctor for `AgentAquariumSetting` sets it vtable to +8. Not sure what's going on there, doesn't make sense.

Update data.yml, Add AgentInventoryContext::InventoryContextEvent

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInventory.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInventoryContext.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismPrismSetConvert.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModuleInterface.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitManager.cs
ida/data.yml

Thought I'd PR before it gets even more.

Update various thingies

---

FFXIVClientStructs/FFXIV/Client/System/Configuration/CharamakeAvatarSaveDataContainer.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
ida/data.yml

- Obsoletes the SavedAppearanceData struct.
- Struct names are from the csv, except for FreeTrialContainer which didn't exist back then.
- Didn't really do much to SavedAppearanceSlot - just added the CustomizeDataHash and Timestamp fields, and replaced the bool IsCreated with a Status enum.

Add CharamakeAvatarSaveDataContainer

---

FFXIVClientStructs/FFXIV/Client/System/String/Utf8String.cs
ida/data.yml

**Summary:**
- Added an `AllowedEntities` enum for the `Utf8String.SanitizeString` function.
- Added `Utf8String.GetParts`, which extracts the different texts and payloads from a string and adds them to a vector.
---
**Regarding SanitizeString:**
The commonly used flags 0x27F, which I don't know where those comes from, allow the following:
- UppercaseLetters
- LowercaseLetters
- Numbers
- SpecialCharacters
- CharacterList
- NewLines
- Payloads
- Unknown9 (Chinese/Korean client specific?)
---
**GetParts Example:**
```cs
var str = Utf8String.FromSequence(ReadOnlySeString.FromMacroString("<string(gstr1)><string(gstr2)><bold(1)>Hello @ World<bold(0)>"));
var vector = new StdVector<Utf8StringPart>();
str->GetParts(&vector);
foreach (var part in vector)
{
ImGui.TextUnformatted($"Payload: {new …
```

Update Utf8String.SanitizeString, add GetParts

---

CExporter/Extensions.cs
FFXIVClientStructs/FFXIV/Component/Completion/CategoryData.cs
FFXIVClientStructs/FFXIV/Component/Completion/CompletionModule.cs
FFXIVClientStructs/Interop/StringPointer.cs

Renaming the type to better reflect that it's a pointer type.
For reference, Pohky said I can still rename it: https://discord.com/channels/581875019861328007/1246473943548825730/1334184320604176455

Rename CString to StringPointer

---

FFXIVClientStructs/FFXIV/Client/Game/Conditions.cs

Turns out not having named fields is pretty annoying while reverse engineering...
Other changes:
- Renamed a couple fields (the first 24 are based on CharacterMode):
- NormalConditions -> Normal
- Unconscious -> Dead
- OperatingSiegeMachine -> AnimLock
- CarryingObject -> Carrying
- Mounted2 -> RidingPillion
- Obsoleted all static properties. I don't think it's worth keeping them.
- Added a float at the end, which is set in the `SetCondition` function.
- Dropped comments as LogMessage RowIds can be retrieved from the Condition sheet.

Switch to Conditions fields

---

FFXIVClientStructs/FFXIV/Client/Game/Event/CustomTalkEventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/LuaEventHandler.cs

The lua scripts use enums that map the Key from the added LuaEventHandlerLuaText struct to the Key from the StdMap as value.
When they are handled, these values resolve to the strings in this StdMap, usually texts from `custom/` sheets.

Add LuaTexts to LuaEventHandler

---

FFXIVClientStructs/FFXIV/Client/Game/Character/LookAtContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/CharaCard.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerEditor.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerInterface.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerPreview.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCharaCard.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/BannerHelper.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/BannerModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaView.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaViewPortrait.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/CurrencySettingsHelper.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/HelperInterface.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
FFXIVClientStructs/FFXIV/Client/UI/Misc/UIModuleHelpers.cs
FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIInputModule.cs
FFXIVClientStructs/FFXIV/Component/Exd/ExdModule.cs
ida/data.yml

Added:
- BannerHelper
- CharaCard
- BannerData, CharaCardData, Data8, Data16, Data32 (names from GM command handler)
- AgentBannerPreview
- AgentBannerPreviewState
- HelperInterface
Updated:
- AgentCharaCard
- AgentBannerEditorState
- CharaView
- CharaViewPortrait
- RaptureGearsetModule
- UIModuleHelpers
- data.yml
Closes #1269

Update Portrait/Adventurer Plate structs

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkArrayData.cs
ida/data.yml

The SubscribedAddons array most likely got bigger, but I still can't find a length in the exe.
Anyhow, that's why the offset of `SubscribedAddonsCount` shifted.

Fix offset of AtkArrayData.SubscribedAddonsCount

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
FFXIVClientStructs/FFXIV/Client/UI/UIModuleInterface.cs
ida/data.yml

Found out that there are helper functions on this `UIModuleAgentModulePtrStruct`, so here we go renaming it.

Add AgentHelpers

---

FFXIVClientStructs/FFXIV/Client/Network/PacketDispatcher.cs

They are getting passed argument 2 (`uint targetId`) of `PacketDispatcher.OnReceivePacket`, not argument 1 (`PacketDispatcher* this`).
While none of these functions are using argument 1, it's still wrong.

Fix PacketDispatcher statics

---

FFXIVClientStructs/FFXIV/Client/Game/HousingManager.cs
FFXIVClientStructs/FFXIV/Client/Game/IndoorTerritory.cs
FFXIVClientStructs/FFXIV/Client/Game/OutdoorTerritory.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
FFXIVClientStructs/FFXIV/Client/Game/WorkshopTerritory.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHousingPortal.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHousingSignboard.cs
ida/data.yml

- Adds the `Client::Game::HouseId` struct we've been working on in the Dalamud Discord.
- Adds `Client::Game::UI::Map.AddHousingMarker`
- Adds `Client::UI::Agent::AgentHousingSignboard.ReadPacket`
- Adds `Client::UI::Agent::AgentHousingPortal.ReadPacket`
(I intend to maybe hook those in the future)

Add HouseId, AgentHousingSignboard, AgentHousingPortal

---

FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCharaCard.cs

The index byte corresponds to a decoration type, such as backing, pattern overlay, etc.

AgentCharaCard: Add DecorationType

---

FFXIVClientStructs/FFXIV/Common/Lua/LuaState.cs
FFXIVClientStructs/FFXIV/Common/Lua/lstate.cs

I accidentally removed this in #1318.
It's actually part of lua: https://www.lua.org/manual/5.3/manual.html#lua_tostring

Add back lua_tostring

---

FFXIVClientStructs/FFXIV/Client/Game/Character/TimelineContainer.cs

These moved by 2 bytes, but it appears OverallSpeed is in the same spot from what I can tell

Fix timeline override offsets for 7.2

---

FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Device.cs

Tested in my own CustomResolution plugin using the following kludge:
I was able to read out `FrameRate` as well, but haven't found the new offsets of all fields following that.

Update Kernel::Device hWnd and adjacent field offsets

---

FFXIVClientStructs/FFXIV/Client/Game/Gauge/JobGauges.cs

Updating offsets since `ElementTimeRemaining` was removed from the job entirely.

Updating BackMageGauge

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/Camera.cs

Calculated this based on the movement of NearPlane/FarPlane, which I use, others are an educated guess as ProjectionMatrix is correct.

Fix render camera offsets for 7.2

---

FFXIVClientStructs/FFXIV/Client/Game/Character/TimelineContainer.cs

Some other stuff was also updated by @Haselnussbomber but not sure about those. I confirmed for Flags3 though (used by `Character.IsWeaponDrawn`).

Fix Character.IsWeaponDrawn

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/Camera.cs

7.2 introduced a new `FoV_2` field that is set when `FoV` setter is called with a boolean flag, from my small amount of testing it's always called with that flag set and I haven't found anything that reads it. If anyone wants to look further into this, the relevant method is `FUN_14059fc20`.

Fix Client::Graphics::Render::Camera FoV offset

---

FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Demihuman.cs

b484eac4abb2368062ef46b1b5d54cf10344978b adjusted `Monster`, `Human` and `Weapon` after `CharacterBase` grew in size, but it seems `Demihuman` was forgotten. This fixes that.

Probably fix `Demihuman` offsets for 7.2

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
FFXIVClientStructs/FFXIV/Client/Game/MJI/MJIManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/GameWindow.cs
ida/data.yml

- The GameWindow struct is much smaller. The UserName field moved further down, after Cursor and Framework pointers, so I had to remove it, since it's not part of the GameWindow struct.
- Switched `MJIManager.Instance()` from static MemberFunction to StaticAddress, in order for structimporter to correctly set the pointer type on the address.
- Updated data.yml
- Removed all `pointer: False`, because if not set false is the default
- Changed `pointer: True` to `pointer: true`, as per [yaml 1.2 spec](https://yaml.org/spec/1.2.2/#10212-boolean) this should be lower cased
- Added `pointer: true` where they were missing
- Removed `InventoryManager.Containers` again. This was added 2 weeks ago, but the entries are missing the InventoryContainers vtable, so absolutely incorrect.

Fix GameWindow size, data.yml Pointers

---

FFXIVClientStructs/FFXIV/Client/Game/BGMSystem.cs
FFXIVClientStructs/FFXIV/Client/Game/CSBonusManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Control/CameraManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Control/Control.cs
FFXIVClientStructs/FFXIV/Client/Game/Control/TargetSystem.cs
FFXIVClientStructs/FFXIV/Client/Game/Event/EventFramework.cs
FFXIVClientStructs/FFXIV/Client/Game/Fate/FateManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Group/GroupManager.cs
FFXIVClientStructs/FFXIV/Client/Game/HousingManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObjectManager.cs
FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Render/OffscreenRenderingManager.cs
FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterUtility.cs
FFXIVClientStructs/FFXIV/Client/Sound/SoundManager.cs
FFXIVClientStructs/FFXIV/Client/System/File/FileManager.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/Framework.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/GameWindow.cs
FFXIVClientStructs/FFXIV/Client/System/Framework/TaskManager.cs
FFXIVClientStructs/FFXIV/Client/System/Input/Cursor.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/ActionTimelineManager.cs
FFXIVClientStructs/FFXIV/Client/System/Scheduler/Resource/SchedulerResourceManagement.cs
FFXIVClientStructs/FFXIV/Client/System/Threading/ThreadManager.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/CharaSelectCharacterList.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkStage.cs
ida/data.yml

I updated several Instance getters to make sure the scripts set the types for global addresses correctly.
- Changed some MemberFunction Instance getters to StaticAddress
- Updated CameraManagers function Instance getter to StaticAddress
- Fixed ActionTimelineManager Instance getter, which was missing `isPointer: true`
- Added missing `isPointer: ` for readability
- Moved Instance getters above fields for readability
- Added missing Instance getters
The only issue remains is `MacroDecoder.GetMacroTime()`, which is incorrectly detected as Instance getter for `Component::Text::MacroDecoder` (currently at 0x1428EE518).

Instance getters cleanup

---

FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs

- `EndTimestamp` seems to hold EndTimestamp from Gold Saucer events.
- `DataId` use depends on `MarkerType` (fate ID for fates, sequential numbers for "escort" arrow quest markers, copy of ObjectiveId for quests, others unknown).
- `MarkerType` indicates the type of marker (0 seems generic, 1 is fates, 3 is quests, 4 is "escort" arrow quest markers, others unknown)
- `EventState` seems used to mark the state of some types (usually -1, but can be 0 for MSQ quests, 2 for completed quests, seems to maybe also indicate something about housing state)

Add some fields to MapMarkerData

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs

the array that contains all market selling items prices in current retainer.
used in my plugin for a long time and i think it's better to move it to FFCS
Example code:
```
private static ulong GetRetainerMarketPrice(ushort slot)
{
if (slot >= 20) return 0;
var manager = InventoryManager.Instance();
if (manager == null) return 0;
var container = manager->GetInventoryContainer(InventoryType.RetainerMarket);
if (container == null || !container->IsLoaded) return 0;
var slotData = container->GetInventorySlot(slot);
if (slotData == null) return 0;
var marketPrices = (ulong*)((byte*)manager + 8632);
return marketPrices[slot];
}
```

Add RetainerItemsPrices to InventoryManager

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryType.cs

The content of these types is not part of the InventoryManager though, as `InventoryManager.GetInventoryContainer` resolves them differently. There is a new inventory thing at 142965D90 with specialized containers. The one I looked at (at 1422E89C0) checks TerritoryIntendedUse == 60 (Cosmic Exploration) and communicates with WKSManager.

Add Cosmopouch InventoryTypes

---

FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSResearch.cs
ida/data.yml

Based on https://ffxiv.consolegameswiki.com/wiki/Cosmic_Tools: each tool has 9 stages (not ranks) with up to 4 types each.
This PR fixes the way things are named.

Fix WKSResearch naming

---

FFXIVClientStructs/FFXIV/Client/Game/Event/EventHandler.cs
FFXIVClientStructs/FFXIV/Client/Game/HousingManager.cs
FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs

See title. No clue if this is breaking. No properties are removed in any case, so as long as adding methods and interfaces to structs is fine, this should be no issue.

Make ID structs equatable and comparable.

---

FFXIVClientStructs/FFXIV/Client/Game/DomanEnclaveManager.cs
FFXIVClientStructs/FFXIV/Client/Game/ReconstructionBoxManager.cs
FFXIVClientStructs/FFXIV/Common/Component/Excel/ExcelSheetWaiter.cs
ida/data.yml

Besides the state being in its own struct (and heavily inlined), the manager is also used to decide which SharedGroup layout instance to display.
So it made sense to rename and replace it with a whole new struct, imo.

Replace ReconstructionBoxManager with DomanEnclaveManager

---

FFXIVClientStructs/FFXIV/Client/Game/UI/NpcYell.cs
FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
ida/data.yml

When I added this I only saw it being called from GoldSaucer related code.
As per [comment](https://github.com/aers/FFXIVClientStructs/pull/1412#issuecomment-2838304048) in #1412 and further reverse-engineering, I'm hereby renaming it to NpcYell.

Rename GoldSaucerYell to NpcYell

---

FFXIVClientStructs/FFXIV/Application/Network/ChatClient.cs
FFXIVClientStructs/FFXIV/Application/Network/NetworkModule.cs
FFXIVClientStructs/FFXIV/Application/Network/ZoneClient.cs
ida/data.yml

I renamed `ZoneConnection` and `ChatConnection` to `ZoneClient` and `ChatClient` to better match the RTTI naming conventions. 
Open to suggestions if there is a better name.

Update data.yml and NetworkModule

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkTexture.cs

This may help people avoid the pitfall that is the default argument on LoadTexture poisoning the games texture cache when used before the game loads the texture itself.
When LoadTexture is called with a hardcoded value of 1, the game will attempt to load the texture in low-resolution mode.
Specifically what this means is the game will not add "_hr1" to the texture path, and will just load whatever texture it is told to load. 
The catch here is, if a plugin tries to load a texture and does specify a "_hr1" texture, when the LoadTexture call is invoked before the game has loaded that texture on its own, it ends up corrupting the internal size of the parts created with that texture, with the size and position data from the higher resolution texture file.
The LoadTexture function internally …

Add LoadTextureWithDefaultVersion

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkExternalInterface.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkModuleEvent.cs

Without the return value, hooking `AtkExternalInterface.CallHandler` will cause a crash.
I'm not sure if `AtkExternalInterface.PlaySoundEffect` and `AtkModuleEvent.CallHandler` are also missing the return value, so I didn't include them.

Fix AtkExternalInterface.CallHandler return value

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentSlider.cs

Turns out these fields are not set automatically via InitializeFromComponentData

AtkComponentSlider more params

---

FFXIVClientStructs/FFXIV/Client/Game/ContentInventoryContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/ContentInventoryItem.cs
FFXIVClientStructs/FFXIV/Client/Game/ContentInventoryManager.cs
FFXIVClientStructs/FFXIV/Client/Game/ContentInventoryProvider.cs
FFXIVClientStructs/FFXIV/Client/Game/InventoryContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/InventoryItem.cs
FFXIVClientStructs/FFXIV/Client/Game/InventoryType.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSContentInventoryContainer.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSContentInventoryItem.cs
FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSContentInventoryProvider.cs
ida/data.yml

I assume it's meant for "content" since it has functions to check the TerritoryTypeId, but currently the `ContentInventoryManager` only has a single inventory provider (`WKSInventoryProvider`) and nothing more.
There are still a couple unnamed vfuncs. I didn't care that much.
Breaking Changes:
- `InventoryContainer.Size`/`GetSize` were changed from `uint` to `int`, because `Client::Game::ContentInventoryContainer.GetSize` returns `-1`.
- `InventoryItem.Dtor` was missing the `freeFlags` parameter.

Add ContentInventoryManager

---

FFXIVClientStructs/FFXIV/Component/GUI/AtkTextNode.cs

It seems the Elipsis flag has moved, I do not know if FixedFontResolution is still correct or not.
1 << 8, seems to cause the text to ignore Alignment and clips the text to the bounds of the node.

TextFlags Fix

---

FFXIVClientStructs/FFXIV/Client/System/Resource/ResourceEventListener.cs
ida/data.yml

For example, this is used by LuaScriptLoader to load Lua scripts
from the resource system.

Add known virtual function used to load in ResourceEventListener

---

FFXIVClientStructs/FFXIV/Client/Game/UI/PvPProfile.cs

Fixes the PvPProfile offsets for Frontline matches and Crystalline Conflict ranks.

Fix 7.3 PvPProfile offsets

---

FFXIVClientStructs/FFXIV/Client/Game/Object/GameObject.cs
ida/data.yml

Adds GetNamePlateColor.
This function is often used to check if a gameobject is hostile but essentially gets the color bytes (saved colors in user config) for certain types of mobs.
These are some of the mapped out ones but wasn't sure whether to include it/how to format it for better info: 
// 4, 5, 6: Enemy players in PvP
// 7: yellow, can be attacked, not engaged
// 8: dead
// 9: red, engaged with your party
// 10: purple, engaged with other party
// 11: orange, aggro'd to your party but not attacked yet
Also doublechecked that this is a different function/doesn't overlap with #1539

Add GameObject.GetNamePlateColorType

---

FFXIVClientStructs/FFXIV/Client/Graphics/Render/GraphicsConfig.cs

This field controls the Jitter multiplier if TSCMAA + Camera Jitter or DLSS are enabled.

Add GraphicsConfig.JitterMultiplier

---

FFXIVClientStructs/FFXIV/Application/Network/WorkDefinitions/ClientSelectData.cs
FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs
ida/data.yml

There's a new function in DrawDataContainer to set this flag, like
for other things like closing the visor. And since it's a new flag,
it also has a corresponding config flag ClientSelectData.

Add HideViera ears option to ClientSelectData, and add function

---

ida/ffxiv_exdgetters.py
ida/ffxiv_structimporter.py
ida/ida_wrapper.py

**The version of `ffxiv_structs.yml` in HEAD contains duplicate and overlapping fields. In order to test this PR, you must use the version attached to this PR: [ffxiv_structs.yml](https://github.com/user-attachments/files/21939195/ffxiv_structs.yml)**
These changes have been tested and are stable on IDA Pro 9.2b. I am unable to test on older versions of IDA and request that others with access to those versions ensure that the scripts run and produce the expected output still.
The IDA Pro 9.0b version which was leaked earlier this year will not be supported as the `ida_typeinf` changes were half-baked and are missing a lot of required functions and constructors. As such, officially, we should only support full release versions for 7.x, 8.x, and 9.x through 9.2.
For bitfield enums in IDA …

Add support for IDA Pro 9.0 - 9.2

---

FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/MaterialResourceHandle.cs

Since 7.0, most color tables are 8x32 (32 rows of 8 vectors of 2 `Half`s, i. e. 2048 bytes) but some legacy ones are still 4x16 (512 bytes), making these structures and accessors very wrong since then.
On top of the things being variable-size, a lot of the columns also have variable semantics (which depend on the exact shader set picked by a material), making it hard to do better than providing spans of `Half`s for the color table and of `byte`s for the stain table and letting the callers cross-reference with shaders.

Update MaterialResourceHandle for variable-size color tables used since 7.0

---

ida/ffxiv_exdgetters.py
ida/ffxiv_structimporter.py
ida/ida_wrapper.py

This change is primarily targeting IDA 9.x+ where duplicate enum member names can result in lingering members during cleanup, but I've also included an implementation for 7.x and 8.x for functional parity.
I've also reverted the back-to-front experiment as it did not improve performance on 9.x (WTF did you do, Hex-Rays?)

Fully cleanup enums before recreating

---

FFXIVClientStructs/FFXIV/Client/Game/UI/TerritoryInfo.cs
ida/data.yml

a case i see is to set the misdirection status beacon

Add LoadAreaVFXToLocalPlayer to TerritoryInfo

---

ida/data.yml

used in setting texts in agent, for addon to display current world name and target world name when the world travel request is ready

Add SetupWorldTravelInfo tp data.yml

---

FFXIVClientStructs/FFXIV/Client/Game/WKS/WKSManager.cs

I don't know what the `+ 5` is for, I might be wrong about the shape of this field but this is how it's accessed in `Client::UI::Agent::AgentWKSMission_GetMissionLog` and it yields correct results

Add mission completion fields to WKSManager

---

FFXIVClientStructs/FFXIV/Client/Game/InventoryItem.cs
FFXIVClientStructs/FFXIV/Client/UI/AddonItemDetailCompare.cs
FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemComp.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEvent.cs
FFXIVClientStructs/FFXIV/Component/GUI/AtkEventData.cs

Reverses AddonItemDetailCompare and AgentItemComp
Also adds a new AtkEvent found while reversing the addon, as well as two parameter-fetching functions used in AgentItemComp to more easily get equipment stats/params

AgentItemComp and AddonItemDetailCompare

---

FFXIVClientStructs/FFXIV/Client/UI/AddonCastBarEnemy.cs

Also adds `Unk11`, it's accessed by the same function but unsure what it's for

Add Interruptible to AddonCastBarEnemy
